/*
 * File: app/controller/LookupTables.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TestApp.controller.LookupTables', {
    extend: 'Ext.app.Controller',

    models: [
//        'LookupTable',
        'UserTree'
    ],
    stores: [
//        'LookupData',
        'UserListTree'
    ],

    initLookupTableStores: function(component, eOpts) {

        this.getUserListTreeStore().proxy.url = "./lib/data/userlist.json";
        this.getUserListTreeStore().load();

    },

    init: function(application) {
        this.control({
            "viewport": {
                afterrender: this.initLookupTableStores
            }
        });
    }

});
