/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.minpanel',
    requires: ['Ext.chart.*', 'Ext.Toolbar'],

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var chart = button.up('panel').down('chart'),
                                newStore = Ext.getStore('StackedColumnStoreReload');

                            chart.bindStore(newStore);
                            chart.redraw(true);
                        },
                        text: 'new data'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var chart = button.up('panel').down('chart'),
                                newStore = Ext.getStore('StackedColumnStore');

                            chart.bindStore(newStore);
                            chart.redraw(true);
                        },
                        text: 'reset data'
                    },
                    {
                        xtype: 'spacer'
                    }
                ]
            },
            {
                xtype: 'chart',
                interactions: ['itemhighlight'],
                data: {
                    x: 'foo',
                    y1: 20,
                    y2: 20,
                    y3: 20,
                    y4: 20,
                    y5: 20
                },
                colors: [
                    '#115fa6',
                    '#94ae0a',
                    '#a61120',
                    '#ff8809',
                    '#ffd13e',
                    '#a61187',
                    '#24ad9a',
                    '#7c7474',
                    '#a66111'
                ],
                store: 'StackedColumnStore',
                axes: [
                    {
                        type: 'category'
                    },
                    {
                        type: 'numeric',
                        position: 'left'
                    }
                ],
                series: [
                    {
                        type: 'bar',
                        highlightCfg: {
                            strokeStyle: 'red',
                            lineWidth: 3
                        },
                        xField: 'x',
                        yField: [
                            'y1',
                            'y2',
                            'y3',
                            'y4',
                            'y5'
                        ],
                        label: {
                            field: ['y1', 'y2', 'y3', 'y4', 'y5'],
                            display: 'insideEnd'
                        }
                    }
                ]
            }
        ]
    }

});