/*
 * File: app/store/StackedColumStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.StackedColumStore', {
    extend: 'Ext.data.Store',

    config: {
        data: [
            {
                x: 'foo1',
                y1: 16,
                y2: 17,
                y3: 18,
                y4: 19,
                y5: 20
            },
            {
                x: 'foo2',
                y1: 16,
                y22: 17,
                y3: 18,
                y4: 19,
                y5: 20
            },
            {
                x: 'foo3',
                y1: -16,
                y22: -17,
                y3: -18,
                y4: -19,
                y5: -20
            },
            {
                x: 'foo4',
                y1: 16,
                y22: 17,
                y3: -18,
                y4: -19,
                y5: 20
            }
        ],
        storeId: 'StackedColumnStore',
        fields: ['x', 'y1', 'y2', 'y3', 'y4', 'y5']
    }
});