/*
 * File: app/controller/HomeMenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.HomeMenuController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            nav: '#appNav'
        },

        control: {
            "#homeMenu": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        var menuKey = record.get('Id');
        var className;
        if(menuKey == 'journeyplanner')
        {
            className = 'MyApp.view.JourneyPlanner';
        } else if (menuKey == 'aroundme')
        {
            className = 'MyApp.view.Map';
        }

        this.getNav()
        .push(Ext.create(className, {
            title: record.get('Title')
        }));
    },

    launch: function() {


    },

    init: function(application) {

    }

});