/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
Ext.Boot.loadSyncBasePrefix([
  "classic/classic/.sencha/package/Boot.js",
  "packages/core/src/Ext.js",
  "packages/core/src/lang/Error.js",
  "packages/core/src/lang/Array.js",
  "packages/core/src/lang/Assert.js",
  "packages/core/src/lang/String.js",
  "packages/core/src/lang/Date.js",
  "packages/core/src/lang/Function.js",
  "packages/core/src/lang/Number.js",
  "packages/core/src/lang/Object.js",
  "packages/core/src/Util.js",
  "packages/core/src/util/Version.js",
  "packages/core/src/class/Config.js",
  "packages/core/src/class/Configurator.js",
  "packages/core/src/class/Base.js",
  "packages/core/src/util/Cache.js",
  "packages/core/src/class/Class.js",
  "packages/core/src/class/Inventory.js",
  "packages/core/src/class/ClassManager.js",
  "packages/core/src/env/Browser.js",
  "packages/core/src/env/OS.js",
  "packages/core/src/env/Feature.js",
  "packages/core/src/env/Ready.js",
  "packages/core/src/class/Loader.js",
  "classic/classic/overrides/Positionable.js",
  "classic/classic/overrides/event/Event.js",
  "classic/classic/overrides/event/publisher/Dom.js",
  "classic/classic/overrides/event/publisher/Gesture.js",
  "classic/classic/overrides/dom/Element.js",
  "classic/classic/overrides/GlobalEvents.js",
  "classic/classic/overrides/Widget.js",
  "classic/classic/overrides/app/domain/Component.js",
  "packages/core/overrides/app/Application.js",
  "classic/classic/overrides/app/Application.js",
  "classic/classic/overrides/dom/Helper.js",
  "classic/classic/overrides/plugin/Abstract.js",
  "packages/charts/classic/overrides/AbstractChart.js"
]);

