/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
Ext.Loader.addBaseUrlClassPathMappings({
  "Ext": "classic/classic/src",
  "Ext.AbstractManager": "packages/core/src/AbstractManager.js",
  "Ext.Ajax": "packages/core/src/Ajax.js",
  "Ext.AnimationQueue": "packages/core/src/AnimationQueue.js",
  "Ext.Array": "packages/core/src/lang/Array.js",
  "Ext.Assert": "packages/core/src/lang/Assert.js",
  "Ext.Base": "packages/core/src/class/Base.js",
  "Ext.Boot": "classic/classic/.sencha/package/Boot.js",
  "Ext.Class": "packages/core/src/class/Class.js",
  "Ext.ClassManager": "packages/core/src/class/ClassManager.js",
  "Ext.ComponentManager": "packages/core/src/ComponentManager.js",
  "Ext.ComponentQuery": "packages/core/src/ComponentQuery.js",
  "Ext.Config": "packages/core/src/class/Config.js",
  "Ext.Configurator": "packages/core/src/class/Configurator.js",
  "Ext.Date": "packages/core/src/lang/Date.js",
  "Ext.Error": "packages/core/src/lang/Error.js",
  "Ext.Evented": "packages/core/src/Evented.js",
  "Ext.Factory": "packages/core/src/mixin/Factoryable.js",
  "Ext.Function": "packages/core/src/lang/Function.js",
  "Ext.GlobalEvents": "packages/core/src/GlobalEvents.js",
  "Ext.Inventory": "packages/core/src/class/Inventory.js",
  "Ext.JSON": "packages/core/src/JSON.js",
  "Ext.Loader": "packages/core/src/class/Loader.js",
  "Ext.Mixin": "packages/core/src/class/Mixin.js",
  "Ext.Msg": "classic/classic/src/window/MessageBox.js",
  "Ext.Number": "packages/core/src/lang/Number.js",
  "Ext.Object": "packages/core/src/lang/Object.js",
  "Ext.Script": "packages/core/src/class/Inventory.js",
  "Ext.String": "packages/core/src/lang/String.js",
  "Ext.String.format": "packages/core/src/Template.js",
  "Ext.TaskQueue": "packages/core/src/TaskQueue.js",
  "Ext.Template": "packages/core/src/Template.js",
  "Ext.Util": "packages/core/src/Util.js",
  "Ext.Version": "packages/core/src/util/Version.js",
  "Ext.Widget": "packages/core/src/Widget.js",
  "Ext.XTemplate": "packages/core/src/XTemplate.js",
  "Ext.app": "packages/core/src/app",
  "Ext.app.bindinspector": "classic/classic/src/app/bindinspector",
  "Ext.browser": "packages/core/src/env/Browser.js",
  "Ext.chart": "packages/charts/src/chart",
  "Ext.chart.LegendBase": "packages/charts/classic/src/chart/LegendBase.js",
  "Ext.chart.TipSurface": "packages/charts/classic/src/chart/TipSurface.js",
  "Ext.chart.interactions.ItemInfo": "packages/charts/classic/src/chart/interactions/ItemInfo.js",
  "Ext.chart.overrides": "packages/charts/classic/overrides",
  "Ext.class": "packages/core/src/class",
  "Ext.data": "packages/core/src/data",
  "Ext.direct": "packages/core/src/direct",
  "Ext.dom": "packages/core/src/dom",
  "Ext.dom.ButtonElement": "classic/classic/src/dom/ButtonElement.js",
  "Ext.dom.Layer": "classic/classic/src/dom/Layer.js",
  "Ext.draw": "packages/charts/src/draw",
  "Ext.draw.ContainerBase": "packages/charts/classic/src/draw/ContainerBase.js",
  "Ext.draw.SurfaceBase": "packages/charts/classic/src/draw/SurfaceBase.js",
  "Ext.draw.engine.SvgContext.Gradient": "packages/charts/src/draw/engine/SvgContext.js",
  "Ext.env": "packages/core/src/env",
  "Ext.event": "packages/core/src/event",
  "Ext.event.publisher.MouseEnterLeave": "classic/classic/src/event/publisher/MouseEnterLeave.js",
  "Ext.feature": "packages/core/src/env/Feature.js",
  "Ext.fx.Animation": "packages/core/src/fx/Animation.js",
  "Ext.fx.Runner": "packages/core/src/fx/Runner.js",
  "Ext.fx.State": "packages/core/src/fx/State.js",
  "Ext.fx.animation": "packages/core/src/fx/animation",
  "Ext.fx.easing": "packages/core/src/fx/easing",
  "Ext.fx.layout": "packages/core/src/fx/layout",
  "Ext.fx.runner": "packages/core/src/fx/runner",
  "Ext.lang": "packages/core/src/lang",
  "Ext.mixin": "packages/core/src/mixin",
  "Ext.os": "packages/core/src/env/OS.js",
  "Ext.overrides": "classic/classic/overrides",
  "Ext.overrides.util.Positionable": "classic/classic/overrides/Positionable.js",
  "Ext.perf": "packages/core/src/perf",
  "Ext.plugin.Abstract": "packages/core/src/plugin/Abstract.js",
  "Ext.plugin.LazyItems": "packages/core/src/plugin/LazyItems.js",
  "Ext.scroll": "packages/core/src/scroll",
  "Ext.supports": "packages/core/src/env/Feature.js",
  "Ext.util": "packages/core/src/util",
  "Ext.util.Animate": "classic/classic/src/util/Animate.js",
  "Ext.util.CSS": "classic/classic/src/util/CSS.js",
  "Ext.util.ClickRepeater": "classic/classic/src/util/ClickRepeater.js",
  "Ext.util.ComponentDragger": "classic/classic/src/util/ComponentDragger.js",
  "Ext.util.Cookies": "classic/classic/src/util/Cookies.js",
  "Ext.util.ElementContainer": "classic/classic/src/util/ElementContainer.js",
  "Ext.util.Floating": "classic/classic/src/util/Floating.js",
  "Ext.util.FocusTrap": "classic/classic/src/util/FocusTrap.js",
  "Ext.util.Focusable": "classic/classic/src/util/Focusable.js",
  "Ext.util.FocusableContainer": "classic/classic/src/util/FocusableContainer.js",
  "Ext.util.Format.format": "packages/core/src/Template.js",
  "Ext.util.KeyMap": "classic/classic/src/util/KeyMap.js",
  "Ext.util.KeyNav": "classic/classic/src/util/KeyNav.js",
  "Ext.util.KeyboardInteractive": "classic/classic/src/util/KeyboardInteractive.js",
  "Ext.util.Memento": "classic/classic/src/util/Memento.js",
  "Ext.util.ProtoElement": "classic/classic/src/util/ProtoElement.js",
  "Ext.util.Queue": "classic/classic/src/util/Queue.js",
  "Ext.util.Renderable": "classic/classic/src/util/Renderable.js",
  "Ext.util.StoreHolder": "classic/classic/src/util/StoreHolder.js",
  "Ext.ux.BoxReorderer": "packages/ux/classic/src/BoxReorderer.js",
  "Ext.ux.CellDragDrop": "packages/ux/classic/src/CellDragDrop.js",
  "Ext.ux.DataTip": "packages/ux/classic/src/DataTip.js",
  "Ext.ux.DataView.Animated": "packages/ux/classic/src/DataView/Animated.js",
  "Ext.ux.DataView.DragSelector": "packages/ux/classic/src/DataView/DragSelector.js",
  "Ext.ux.DataView.Draggable": "packages/ux/classic/src/DataView/Draggable.js",
  "Ext.ux.DataView.LabelEditor": "packages/ux/classic/src/DataView/LabelEditor.js",
  "Ext.ux.Explorer": "packages/ux/classic/src/Explorer.js",
  "Ext.ux.FieldReplicator": "packages/ux/classic/src/FieldReplicator.js",
  "Ext.ux.GMapPanel": "packages/ux/classic/src/GMapPanel.js",
  "Ext.ux.GroupTabPanel": "packages/ux/classic/src/GroupTabPanel.js",
  "Ext.ux.GroupTabRenderer": "packages/ux/classic/src/GroupTabRenderer.js",
  "Ext.ux.IFrame": "packages/ux/classic/src/IFrame.js",
  "Ext.ux.LiveSearchGridPanel": "packages/ux/classic/src/LiveSearchGridPanel.js",
  "Ext.ux.PreviewPlugin": "packages/ux/classic/src/PreviewPlugin.js",
  "Ext.ux.ProgressBarPager": "packages/ux/classic/src/ProgressBarPager.js",
  "Ext.ux.RowExpander": "packages/ux/classic/src/RowExpander.js",
  "Ext.ux.SlidingPager": "packages/ux/classic/src/SlidingPager.js",
  "Ext.ux.Spotlight": "packages/ux/classic/src/Spotlight.js",
  "Ext.ux.TabCloseMenu": "packages/ux/classic/src/TabCloseMenu.js",
  "Ext.ux.TabReorderer": "packages/ux/classic/src/TabReorderer.js",
  "Ext.ux.TabScrollerMenu": "packages/ux/classic/src/TabScrollerMenu.js",
  "Ext.ux.ToolbarDroppable": "packages/ux/classic/src/ToolbarDroppable.js",
  "Ext.ux.TreePicker": "packages/ux/classic/src/TreePicker.js",
  "Ext.ux.ajax.DataSimlet": "packages/ux/src/ajax/DataSimlet.js",
  "Ext.ux.ajax.JsonSimlet": "packages/ux/src/ajax/JsonSimlet.js",
  "Ext.ux.ajax.SimManager": "packages/ux/src/ajax/SimManager.js",
  "Ext.ux.ajax.SimXhr": "packages/ux/src/ajax/SimXhr.js",
  "Ext.ux.ajax.Simlet": "packages/ux/src/ajax/Simlet.js",
  "Ext.ux.ajax.XmlSimlet": "packages/ux/src/ajax/XmlSimlet.js",
  "Ext.ux.colorpick.Button": "packages/ux/classic/src/colorpick/Button.js",
  "Ext.ux.colorpick.ButtonController": "packages/ux/classic/src/colorpick/ButtonController.js",
  "Ext.ux.colorpick.ColorMap": "packages/ux/classic/src/colorpick/ColorMap.js",
  "Ext.ux.colorpick.ColorMapController": "packages/ux/classic/src/colorpick/ColorMapController.js",
  "Ext.ux.colorpick.ColorPreview": "packages/ux/classic/src/colorpick/ColorPreview.js",
  "Ext.ux.colorpick.ColorUtils": "packages/ux/classic/src/colorpick/ColorUtils.js",
  "Ext.ux.colorpick.Field": "packages/ux/classic/src/colorpick/Field.js",
  "Ext.ux.colorpick.Selection": "packages/ux/classic/src/colorpick/Selection.js",
  "Ext.ux.colorpick.Selector": "packages/ux/classic/src/colorpick/Selector.js",
  "Ext.ux.colorpick.SelectorController": "packages/ux/classic/src/colorpick/SelectorController.js",
  "Ext.ux.colorpick.SelectorModel": "packages/ux/classic/src/colorpick/SelectorModel.js",
  "Ext.ux.colorpick.Slider": "packages/ux/classic/src/colorpick/Slider.js",
  "Ext.ux.colorpick.SliderAlpha": "packages/ux/classic/src/colorpick/SliderAlpha.js",
  "Ext.ux.colorpick.SliderController": "packages/ux/classic/src/colorpick/SliderController.js",
  "Ext.ux.colorpick.SliderHue": "packages/ux/classic/src/colorpick/SliderHue.js",
  "Ext.ux.colorpick.SliderSaturation": "packages/ux/classic/src/colorpick/SliderSaturation.js",
  "Ext.ux.colorpick.SliderValue": "packages/ux/classic/src/colorpick/SliderValue.js",
  "Ext.ux.dashboard.GoogleRssPart": "packages/ux/classic/src/dashboard/GoogleRssPart.js",
  "Ext.ux.dashboard.GoogleRssView": "packages/ux/classic/src/dashboard/GoogleRssView.js",
  "Ext.ux.data.PagingMemoryProxy": "packages/ux/classic/src/data/PagingMemoryProxy.js",
  "Ext.ux.dd.CellFieldDropZone": "packages/ux/classic/src/dd/CellFieldDropZone.js",
  "Ext.ux.dd.PanelFieldDragZone": "packages/ux/classic/src/dd/PanelFieldDragZone.js",
  "Ext.ux.desktop.App": "packages/ux/classic/src/desktop/App.js",
  "Ext.ux.desktop.Desktop": "packages/ux/classic/src/desktop/Desktop.js",
  "Ext.ux.desktop.Module": "packages/ux/classic/src/desktop/Module.js",
  "Ext.ux.desktop.ShortcutModel": "packages/ux/classic/src/desktop/ShortcutModel.js",
  "Ext.ux.desktop.StartMenu": "packages/ux/classic/src/desktop/StartMenu.js",
  "Ext.ux.desktop.TaskBar": "packages/ux/classic/src/desktop/TaskBar.js",
  "Ext.ux.desktop.TrayClock": "packages/ux/classic/src/desktop/TaskBar.js",
  "Ext.ux.desktop.Video": "packages/ux/classic/src/desktop/Video.js",
  "Ext.ux.desktop.Wallpaper": "packages/ux/classic/src/desktop/Wallpaper.js",
  "Ext.ux.event.Driver": "packages/ux/src/event/Driver.js",
  "Ext.ux.event.Maker": "packages/ux/src/event/Maker.js",
  "Ext.ux.event.Player": "packages/ux/src/event/Player.js",
  "Ext.ux.event.Recorder": "packages/ux/src/event/Recorder.js",
  "Ext.ux.event.RecorderManager": "packages/ux/classic/src/event/RecorderManager.js",
  "Ext.ux.form.ItemSelector": "packages/ux/classic/src/form/ItemSelector.js",
  "Ext.ux.form.MultiSelect": "packages/ux/classic/src/form/MultiSelect.js",
  "Ext.ux.form.SearchField": "packages/ux/classic/src/form/SearchField.js",
  "Ext.ux.google.Api": "packages/ux/src/google/Api.js",
  "Ext.ux.google.Feeds": "packages/ux/src/google/Feeds.js",
  "Ext.ux.grid.SubTable": "packages/ux/classic/src/grid/SubTable.js",
  "Ext.ux.grid.TransformGrid": "packages/ux/classic/src/grid/TransformGrid.js",
  "Ext.ux.rating.Picker": "packages/ux/classic/src/rating/Picker.js",
  "Ext.ux.statusbar.StatusBar": "packages/ux/classic/src/statusbar/StatusBar.js",
  "Ext.ux.statusbar.ValidationStatus": "packages/ux/classic/src/statusbar/ValidationStatus.js"
});

Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractManager": [],
  "Ext.Action": [],
  "Ext.Ajax": [],
  "Ext.AnimationQueue": [],
  "Ext.Component": [
    "Ext.AbstractComponent"
  ],
  "Ext.ComponentLoader": [],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Editor": [],
  "Ext.ElementLoader": [],
  "Ext.EventManager": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.FocusManager": [
    "Ext.FocusMgr"
  ],
  "Ext.GlobalEvents": [
    "Ext.globalEvents"
  ],
  "Ext.Img": [],
  "Ext.LoadMask": [],
  "Ext.Mixin": [],
  "Ext.ProgressBar": [],
  "Ext.ProgressBarWidget": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Widget": [],
  "Ext.XTemplate": [],
  "Ext.ZIndexManager": [
    "Ext.WindowGroup"
  ],
  "Ext.app.Application": [],
  "Ext.app.BaseController": [],
  "Ext.app.Controller": [],
  "Ext.app.EventBus": [],
  "Ext.app.EventDomain": [],
  "Ext.app.Profile": [],
  "Ext.app.Util": [],
  "Ext.app.ViewController": [],
  "Ext.app.ViewModel": [],
  "Ext.app.bind.AbstractStub": [],
  "Ext.app.bind.BaseBinding": [],
  "Ext.app.bind.Binding": [],
  "Ext.app.bind.Formula": [],
  "Ext.app.bind.LinkStub": [],
  "Ext.app.bind.Multi": [],
  "Ext.app.bind.RootStub": [],
  "Ext.app.bind.Stub": [],
  "Ext.app.bind.Template": [],
  "Ext.app.bind.TemplateBinding": [],
  "Ext.app.bindinspector.ComponentDetail": [],
  "Ext.app.bindinspector.ComponentList": [],
  "Ext.app.bindinspector.Container": [],
  "Ext.app.bindinspector.Environment": [],
  "Ext.app.bindinspector.Inspector": [],
  "Ext.app.bindinspector.Util": [],
  "Ext.app.bindinspector.ViewModelDetail": [],
  "Ext.app.bindinspector.noconflict.BaseModel": [],
  "Ext.app.domain.Component": [],
  "Ext.app.domain.Controller": [],
  "Ext.app.domain.Direct": [],
  "Ext.app.domain.Global": [],
  "Ext.app.domain.Store": [],
  "Ext.app.domain.View": [],
  "Ext.app.route.Queue": [],
  "Ext.app.route.Route": [],
  "Ext.app.route.Router": [],
  "Ext.button.Button": [
    "Ext.Button"
  ],
  "Ext.button.Cycle": [
    "Ext.CycleButton"
  ],
  "Ext.button.Manager": [
    "Ext.ButtonToggleManager"
  ],
  "Ext.button.Segmented": [],
  "Ext.button.Split": [
    "Ext.SplitButton"
  ],
  "Ext.chart.AbstractChart": [],
  "Ext.chart.CartesianChart": [
    "Ext.chart.Chart"
  ],
  "Ext.chart.Legend": [],
  "Ext.chart.LegendBase": [],
  "Ext.chart.MarkerHolder": [],
  "Ext.chart.Markers": [],
  "Ext.chart.PolarChart": [],
  "Ext.chart.SpaceFillingChart": [],
  "Ext.chart.TipSurface": [],
  "Ext.chart.axis.Axis": [],
  "Ext.chart.axis.Axis3D": [],
  "Ext.chart.axis.Category": [],
  "Ext.chart.axis.Category3D": [],
  "Ext.chart.axis.Numeric": [],
  "Ext.chart.axis.Numeric3D": [],
  "Ext.chart.axis.Time": [],
  "Ext.chart.axis.Time3D": [],
  "Ext.chart.axis.layout.CombineDuplicate": [],
  "Ext.chart.axis.layout.Continuous": [],
  "Ext.chart.axis.layout.Discrete": [],
  "Ext.chart.axis.layout.Layout": [],
  "Ext.chart.axis.segmenter.Names": [],
  "Ext.chart.axis.segmenter.Numeric": [],
  "Ext.chart.axis.segmenter.Segmenter": [],
  "Ext.chart.axis.segmenter.Time": [],
  "Ext.chart.axis.sprite.Axis": [],
  "Ext.chart.axis.sprite.Axis3D": [],
  "Ext.chart.grid.CircularGrid": [],
  "Ext.chart.grid.HorizontalGrid": [],
  "Ext.chart.grid.HorizontalGrid3D": [],
  "Ext.chart.grid.RadialGrid": [],
  "Ext.chart.grid.VerticalGrid": [],
  "Ext.chart.grid.VerticalGrid3D": [],
  "Ext.chart.interactions.Abstract": [],
  "Ext.chart.interactions.CrossZoom": [],
  "Ext.chart.interactions.Crosshair": [],
  "Ext.chart.interactions.ItemEdit": [],
  "Ext.chart.interactions.ItemHighlight": [],
  "Ext.chart.interactions.ItemInfo": [],
  "Ext.chart.interactions.PanZoom": [],
  "Ext.chart.interactions.Rotate": [],
  "Ext.chart.interactions.RotatePie3D": [],
  "Ext.chart.label.Callout": [],
  "Ext.chart.label.Label": [],
  "Ext.chart.plugin.ItemEvents": [],
  "Ext.chart.series.Area": [],
  "Ext.chart.series.Bar": [],
  "Ext.chart.series.Bar3D": [],
  "Ext.chart.series.CandleStick": [],
  "Ext.chart.series.Cartesian": [],
  "Ext.chart.series.Gauge": [],
  "Ext.chart.series.Line": [],
  "Ext.chart.series.Pie": [],
  "Ext.chart.series.Pie3D": [],
  "Ext.chart.series.Polar": [],
  "Ext.chart.series.Radar": [],
  "Ext.chart.series.Scatter": [],
  "Ext.chart.series.Series": [],
  "Ext.chart.series.StackedCartesian": [],
  "Ext.chart.series.sprite.Aggregative": [],
  "Ext.chart.series.sprite.Area": [],
  "Ext.chart.series.sprite.Bar": [],
  "Ext.chart.series.sprite.Bar3D": [],
  "Ext.chart.series.sprite.Box": [],
  "Ext.chart.series.sprite.CandleStick": [],
  "Ext.chart.series.sprite.Cartesian": [],
  "Ext.chart.series.sprite.Line": [],
  "Ext.chart.series.sprite.Pie3DPart": [],
  "Ext.chart.series.sprite.PieSlice": [],
  "Ext.chart.series.sprite.Polar": [],
  "Ext.chart.series.sprite.Radar": [],
  "Ext.chart.series.sprite.Scatter": [],
  "Ext.chart.series.sprite.Series": [],
  "Ext.chart.series.sprite.StackedCartesian": [],
  "Ext.chart.theme.Base": [],
  "Ext.chart.theme.Blue": [],
  "Ext.chart.theme.BlueGradients": [],
  "Ext.chart.theme.Category1": [],
  "Ext.chart.theme.Category1Gradients": [],
  "Ext.chart.theme.Category2": [],
  "Ext.chart.theme.Category2Gradients": [],
  "Ext.chart.theme.Category3": [],
  "Ext.chart.theme.Category3Gradients": [],
  "Ext.chart.theme.Category4": [],
  "Ext.chart.theme.Category4Gradients": [],
  "Ext.chart.theme.Category5": [],
  "Ext.chart.theme.Category5Gradients": [],
  "Ext.chart.theme.Category6": [],
  "Ext.chart.theme.Category6Gradients": [],
  "Ext.chart.theme.Default": [],
  "Ext.chart.theme.DefaultGradients": [],
  "Ext.chart.theme.Green": [],
  "Ext.chart.theme.GreenGradients": [],
  "Ext.chart.theme.Midnight": [],
  "Ext.chart.theme.Muted": [],
  "Ext.chart.theme.Purple": [],
  "Ext.chart.theme.PurpleGradients": [],
  "Ext.chart.theme.Red": [],
  "Ext.chart.theme.RedGradients": [],
  "Ext.chart.theme.Sky": [],
  "Ext.chart.theme.SkyGradients": [],
  "Ext.chart.theme.Yellow": [],
  "Ext.chart.theme.YellowGradients": [],
  "Ext.container.ButtonGroup": [
    "Ext.ButtonGroup"
  ],
  "Ext.container.Container": [
    "Ext.Container",
    "Ext.AbstractContainer"
  ],
  "Ext.container.DockingContainer": [],
  "Ext.container.Monitor": [],
  "Ext.container.Viewport": [
    "Ext.Viewport"
  ],
  "Ext.dashboard.Column": [],
  "Ext.dashboard.Dashboard": [],
  "Ext.dashboard.DropZone": [],
  "Ext.dashboard.Panel": [],
  "Ext.dashboard.Part": [],
  "Ext.data.AbstractStore": [],
  "Ext.data.ArrayStore": [
    "Ext.data.SimpleStore"
  ],
  "Ext.data.Batch": [],
  "Ext.data.BufferedStore": [],
  "Ext.data.ChainedStore": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.ErrorCollection": [
    "Ext.data.Errors"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonPStore": [],
  "Ext.data.JsonStore": [],
  "Ext.data.LocalStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr"
  ],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [],
  "Ext.data.PageMap": [],
  "Ext.data.ProxyStore": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.Session": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeModel": [],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validation": [],
  "Ext.data.XmlStore": [],
  "Ext.data.field.Boolean": [],
  "Ext.data.field.Date": [],
  "Ext.data.field.Field": [
    "Ext.data.Field"
  ],
  "Ext.data.field.Integer": [],
  "Ext.data.field.Number": [],
  "Ext.data.field.String": [],
  "Ext.data.flash.BinaryXhr": [],
  "Ext.data.identifier.Generator": [],
  "Ext.data.identifier.Negative": [],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.matrix.Matrix": [],
  "Ext.data.matrix.Side": [],
  "Ext.data.matrix.Slice": [],
  "Ext.data.operation.Create": [],
  "Ext.data.operation.Destroy": [],
  "Ext.data.operation.Operation": [
    "Ext.data.Operation"
  ],
  "Ext.data.operation.Read": [],
  "Ext.data.operation.Update": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.data.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.schema.Association": [],
  "Ext.data.schema.ManyToMany": [],
  "Ext.data.schema.ManyToOne": [],
  "Ext.data.schema.Namer": [],
  "Ext.data.schema.OneToOne": [],
  "Ext.data.schema.Role": [],
  "Ext.data.schema.Schema": [],
  "Ext.data.session.BatchVisitor": [],
  "Ext.data.session.ChangesVisitor": [],
  "Ext.data.session.ChildChangesVisitor": [],
  "Ext.data.validator.Bound": [],
  "Ext.data.validator.Email": [],
  "Ext.data.validator.Exclusion": [],
  "Ext.data.validator.Format": [],
  "Ext.data.validator.Inclusion": [],
  "Ext.data.validator.Length": [],
  "Ext.data.validator.List": [],
  "Ext.data.validator.Presence": [],
  "Ext.data.validator.Range": [],
  "Ext.data.validator.Validator": [],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dd.DD": [],
  "Ext.dd.DDProxy": [],
  "Ext.dd.DDTarget": [],
  "Ext.dd.DragDrop": [],
  "Ext.dd.DragDropManager": [
    "Ext.dd.DragDropMgr",
    "Ext.dd.DDM"
  ],
  "Ext.dd.DragSource": [],
  "Ext.dd.DragTracker": [],
  "Ext.dd.DragZone": [],
  "Ext.dd.DropTarget": [],
  "Ext.dd.DropZone": [],
  "Ext.dd.Registry": [],
  "Ext.dd.ScrollManager": [],
  "Ext.dd.StatusProxy": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.ButtonElement": [],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.dom.CompositeElementLite": [
    "Ext.CompositeElementLite"
  ],
  "Ext.dom.Element": [
    "Ext.Element"
  ],
  "Ext.dom.ElementEvent": [],
  "Ext.dom.Fly": [
    "Ext.dom.Element.Fly"
  ],
  "Ext.dom.GarbageCollector": [],
  "Ext.dom.Helper": [
    "Ext.DomHelper",
    "Ext.core.DomHelper"
  ],
  "Ext.dom.Layer": [
    "Ext.Layer"
  ],
  "Ext.dom.Query": [
    "Ext.core.DomQuery",
    "Ext.DomQuery"
  ],
  "Ext.dom.Shadow": [
    "Ext.Shadow"
  ],
  "Ext.dom.Shim": [],
  "Ext.dom.Underlay": [],
  "Ext.dom.UnderlayPool": [],
  "Ext.draw.Animator": [],
  "Ext.draw.Color": [],
  "Ext.draw.Container": [
    "Ext.draw.Component"
  ],
  "Ext.draw.ContainerBase": [],
  "Ext.draw.Draw": [],
  "Ext.draw.LimitedCache": [],
  "Ext.draw.Matrix": [],
  "Ext.draw.Path": [],
  "Ext.draw.PathUtil": [],
  "Ext.draw.Point": [],
  "Ext.draw.SegmentTree": [],
  "Ext.draw.Surface": [],
  "Ext.draw.SurfaceBase": [],
  "Ext.draw.TextMeasurer": [],
  "Ext.draw.TimingFunctions": [],
  "Ext.draw.engine.Canvas": [],
  "Ext.draw.engine.Svg": [],
  "Ext.draw.engine.SvgContext": [],
  "Ext.draw.engine.SvgContext.Gradient": [],
  "Ext.draw.gradient.Gradient": [],
  "Ext.draw.gradient.GradientDefinition": [],
  "Ext.draw.gradient.Linear": [],
  "Ext.draw.gradient.Radial": [],
  "Ext.draw.modifier.Animation": [],
  "Ext.draw.modifier.Highlight": [],
  "Ext.draw.modifier.Modifier": [],
  "Ext.draw.modifier.Target": [],
  "Ext.draw.overrides.Path": [],
  "Ext.draw.overrides.Surface": [],
  "Ext.draw.overrides.sprite.Path": [],
  "Ext.draw.plugin.SpriteEvents": [],
  "Ext.draw.sprite.AnimationParser": [],
  "Ext.draw.sprite.Arc": [],
  "Ext.draw.sprite.Arrow": [],
  "Ext.draw.sprite.AttributeDefinition": [],
  "Ext.draw.sprite.AttributeParser": [],
  "Ext.draw.sprite.Circle": [],
  "Ext.draw.sprite.Composite": [],
  "Ext.draw.sprite.Cross": [],
  "Ext.draw.sprite.Diamond": [],
  "Ext.draw.sprite.Ellipse": [],
  "Ext.draw.sprite.EllipticalArc": [],
  "Ext.draw.sprite.Image": [],
  "Ext.draw.sprite.Instancing": [],
  "Ext.draw.sprite.Line": [],
  "Ext.draw.sprite.Path": [],
  "Ext.draw.sprite.Plus": [],
  "Ext.draw.sprite.Rect": [],
  "Ext.draw.sprite.Sector": [],
  "Ext.draw.sprite.Sprite": [],
  "Ext.draw.sprite.Square": [],
  "Ext.draw.sprite.Text": [],
  "Ext.draw.sprite.Tick": [],
  "Ext.draw.sprite.Triangle": [],
  "Ext.event.Event": [
    "Ext.EventObjectImpl"
  ],
  "Ext.event.gesture.DoubleTap": [],
  "Ext.event.gesture.Drag": [],
  "Ext.event.gesture.EdgeSwipe": [],
  "Ext.event.gesture.LongPress": [],
  "Ext.event.gesture.MultiTouch": [],
  "Ext.event.gesture.Pinch": [],
  "Ext.event.gesture.Recognizer": [],
  "Ext.event.gesture.Rotate": [],
  "Ext.event.gesture.SingleTouch": [],
  "Ext.event.gesture.Swipe": [],
  "Ext.event.gesture.Tap": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Focus": [],
  "Ext.event.publisher.Gesture": [],
  "Ext.event.publisher.MouseEnterLeave": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.flash.Component": [
    "Ext.FlashComponent"
  ],
  "Ext.form.Basic": [
    "Ext.form.BasicForm"
  ],
  "Ext.form.CheckboxGroup": [],
  "Ext.form.CheckboxManager": [],
  "Ext.form.FieldAncestor": [],
  "Ext.form.FieldContainer": [],
  "Ext.form.FieldSet": [],
  "Ext.form.Label": [],
  "Ext.form.Labelable": [],
  "Ext.form.Panel": [
    "Ext.FormPanel",
    "Ext.form.FormPanel"
  ],
  "Ext.form.RadioGroup": [],
  "Ext.form.RadioManager": [],
  "Ext.form.action.Action": [
    "Ext.form.Action"
  ],
  "Ext.form.action.DirectAction": [],
  "Ext.form.action.DirectLoad": [
    "Ext.form.Action.DirectLoad"
  ],
  "Ext.form.action.DirectSubmit": [
    "Ext.form.Action.DirectSubmit"
  ],
  "Ext.form.action.Load": [
    "Ext.form.Action.Load"
  ],
  "Ext.form.action.StandardSubmit": [],
  "Ext.form.action.Submit": [
    "Ext.form.Action.Submit"
  ],
  "Ext.form.field.Base": [
    "Ext.form.Field",
    "Ext.form.BaseField"
  ],
  "Ext.form.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.form.field.ComboBox": [
    "Ext.form.ComboBox"
  ],
  "Ext.form.field.Date": [
    "Ext.form.DateField",
    "Ext.form.Date"
  ],
  "Ext.form.field.Display": [
    "Ext.form.DisplayField",
    "Ext.form.Display"
  ],
  "Ext.form.field.Field": [],
  "Ext.form.field.File": [
    "Ext.form.FileUploadField",
    "Ext.ux.form.FileUploadField",
    "Ext.form.File"
  ],
  "Ext.form.field.FileButton": [],
  "Ext.form.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.form.field.HtmlEditor": [
    "Ext.form.HtmlEditor"
  ],
  "Ext.form.field.Number": [
    "Ext.form.NumberField",
    "Ext.form.Number"
  ],
  "Ext.form.field.Picker": [
    "Ext.form.Picker"
  ],
  "Ext.form.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.form.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.form.field.Tag": [],
  "Ext.form.field.Text": [
    "Ext.form.TextField",
    "Ext.form.Text"
  ],
  "Ext.form.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.form.field.Time": [
    "Ext.form.TimeField",
    "Ext.form.Time"
  ],
  "Ext.form.field.Trigger": [
    "Ext.form.TriggerField",
    "Ext.form.TwinTriggerField",
    "Ext.form.Trigger"
  ],
  "Ext.form.field.VTypes": [
    "Ext.form.VTypes"
  ],
  "Ext.form.trigger.Component": [],
  "Ext.form.trigger.Spinner": [],
  "Ext.form.trigger.Trigger": [],
  "Ext.fx.Anim": [],
  "Ext.fx.Animation": [],
  "Ext.fx.Animator": [],
  "Ext.fx.CubicBezier": [],
  "Ext.fx.DrawPath": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Manager": [],
  "Ext.fx.PropertyHandler": [],
  "Ext.fx.Queue": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Easing": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [
    "Ext.Animator"
  ],
  "Ext.fx.target.Component": [],
  "Ext.fx.target.CompositeElement": [],
  "Ext.fx.target.CompositeElementCSS": [],
  "Ext.fx.target.CompositeSprite": [],
  "Ext.fx.target.Element": [],
  "Ext.fx.target.ElementCSS": [],
  "Ext.fx.target.Sprite": [],
  "Ext.fx.target.Target": [],
  "Ext.grid.CellContext": [],
  "Ext.grid.CellEditor": [],
  "Ext.grid.ColumnComponentLayout": [],
  "Ext.grid.ColumnLayout": [],
  "Ext.grid.ColumnManager": [
    "Ext.grid.ColumnModel"
  ],
  "Ext.grid.NavigationModel": [],
  "Ext.grid.Panel": [
    "Ext.list.ListView",
    "Ext.ListView",
    "Ext.grid.GridPanel"
  ],
  "Ext.grid.RowEditor": [],
  "Ext.grid.RowEditorButtons": [],
  "Ext.grid.Scroller": [],
  "Ext.grid.ViewDropZone": [],
  "Ext.grid.column.Action": [
    "Ext.grid.ActionColumn"
  ],
  "Ext.grid.column.Boolean": [
    "Ext.grid.BooleanColumn"
  ],
  "Ext.grid.column.Check": [
    "Ext.ux.CheckColumn",
    "Ext.grid.column.CheckColumn"
  ],
  "Ext.grid.column.Column": [
    "Ext.grid.Column"
  ],
  "Ext.grid.column.Date": [
    "Ext.grid.DateColumn"
  ],
  "Ext.grid.column.Number": [
    "Ext.grid.NumberColumn"
  ],
  "Ext.grid.column.RowNumberer": [
    "Ext.grid.RowNumberer"
  ],
  "Ext.grid.column.Template": [
    "Ext.grid.TemplateColumn"
  ],
  "Ext.grid.column.Widget": [],
  "Ext.grid.feature.AbstractSummary": [],
  "Ext.grid.feature.Feature": [],
  "Ext.grid.feature.GroupStore": [],
  "Ext.grid.feature.Grouping": [],
  "Ext.grid.feature.GroupingSummary": [],
  "Ext.grid.feature.RowBody": [],
  "Ext.grid.feature.Summary": [],
  "Ext.grid.filters.Filters": [],
  "Ext.grid.filters.filter.Base": [],
  "Ext.grid.filters.filter.Boolean": [],
  "Ext.grid.filters.filter.Date": [],
  "Ext.grid.filters.filter.List": [],
  "Ext.grid.filters.filter.Number": [],
  "Ext.grid.filters.filter.SingleFilter": [],
  "Ext.grid.filters.filter.String": [],
  "Ext.grid.filters.filter.TriFilter": [],
  "Ext.grid.header.Container": [],
  "Ext.grid.header.DragZone": [],
  "Ext.grid.header.DropZone": [],
  "Ext.grid.locking.HeaderContainer": [],
  "Ext.grid.locking.Lockable": [
    "Ext.grid.Lockable"
  ],
  "Ext.grid.locking.RowSynchronizer": [],
  "Ext.grid.locking.View": [
    "Ext.grid.LockingView"
  ],
  "Ext.grid.plugin.BufferedRenderer": [],
  "Ext.grid.plugin.CellEditing": [],
  "Ext.grid.plugin.Clipboard": [],
  "Ext.grid.plugin.DragDrop": [],
  "Ext.grid.plugin.Editing": [],
  "Ext.grid.plugin.HeaderReorderer": [],
  "Ext.grid.plugin.HeaderResizer": [],
  "Ext.grid.plugin.RowEditing": [],
  "Ext.grid.plugin.RowExpander": [],
  "Ext.grid.property.Grid": [
    "Ext.grid.PropertyGrid"
  ],
  "Ext.grid.property.HeaderContainer": [
    "Ext.grid.PropertyColumnModel"
  ],
  "Ext.grid.property.Property": [
    "Ext.PropGridProperty"
  ],
  "Ext.grid.property.Reader": [],
  "Ext.grid.property.Store": [
    "Ext.grid.PropertyStore"
  ],
  "Ext.grid.selection.Cells": [],
  "Ext.grid.selection.Columns": [],
  "Ext.grid.selection.Replicator": [],
  "Ext.grid.selection.Rows": [],
  "Ext.grid.selection.Selection": [],
  "Ext.grid.selection.SelectionExtender": [],
  "Ext.grid.selection.SpreadsheetModel": [],
  "Ext.layout.Context": [],
  "Ext.layout.ContextItem": [],
  "Ext.layout.Layout": [],
  "Ext.layout.SizeModel": [],
  "Ext.layout.component.Auto": [],
  "Ext.layout.component.Body": [],
  "Ext.layout.component.BoundList": [],
  "Ext.layout.component.Component": [],
  "Ext.layout.component.Dock": [
    "Ext.layout.component.AbstractDock"
  ],
  "Ext.layout.component.FieldSet": [],
  "Ext.layout.component.ProgressBar": [],
  "Ext.layout.component.field.FieldContainer": [],
  "Ext.layout.component.field.HtmlEditor": [],
  "Ext.layout.container.Absolute": [
    "Ext.layout.AbsoluteLayout"
  ],
  "Ext.layout.container.Accordion": [
    "Ext.layout.AccordionLayout"
  ],
  "Ext.layout.container.Anchor": [
    "Ext.layout.AnchorLayout"
  ],
  "Ext.layout.container.Auto": [],
  "Ext.layout.container.Border": [
    "Ext.layout.BorderLayout"
  ],
  "Ext.layout.container.Box": [
    "Ext.layout.BoxLayout"
  ],
  "Ext.layout.container.Card": [
    "Ext.layout.CardLayout"
  ],
  "Ext.layout.container.Center": [
    "Ext.ux.layout.Center"
  ],
  "Ext.layout.container.CheckboxGroup": [],
  "Ext.layout.container.Column": [
    "Ext.layout.ColumnLayout"
  ],
  "Ext.layout.container.ColumnSplitter": [],
  "Ext.layout.container.ColumnSplitterTracker": [],
  "Ext.layout.container.Container": [
    "Ext.layout.ContainerLayout"
  ],
  "Ext.layout.container.Dashboard": [],
  "Ext.layout.container.Editor": [],
  "Ext.layout.container.Fit": [
    "Ext.layout.FitLayout"
  ],
  "Ext.layout.container.Form": [
    "Ext.layout.FormLayout"
  ],
  "Ext.layout.container.HBox": [
    "Ext.layout.HBoxLayout"
  ],
  "Ext.layout.container.SegmentedButton": [],
  "Ext.layout.container.Table": [
    "Ext.layout.TableLayout"
  ],
  "Ext.layout.container.VBox": [
    "Ext.layout.VBoxLayout"
  ],
  "Ext.layout.container.border.Region": [],
  "Ext.layout.container.boxOverflow.Menu": [
    "Ext.layout.boxOverflow.Menu"
  ],
  "Ext.layout.container.boxOverflow.None": [
    "Ext.layout.boxOverflow.None"
  ],
  "Ext.layout.container.boxOverflow.Scroller": [
    "Ext.layout.boxOverflow.Scroller"
  ],
  "Ext.menu.CheckItem": [],
  "Ext.menu.ColorPicker": [],
  "Ext.menu.DatePicker": [],
  "Ext.menu.Item": [
    "Ext.menu.TextItem"
  ],
  "Ext.menu.Manager": [
    "Ext.menu.MenuMgr"
  ],
  "Ext.menu.Menu": [],
  "Ext.menu.Separator": [],
  "Ext.mixin.Accessible": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.ComponentDelegation": [],
  "Ext.mixin.Container": [],
  "Ext.mixin.Factoryable": [],
  "Ext.mixin.Hookable": [],
  "Ext.mixin.Identifiable": [],
  "Ext.mixin.Inheritable": [],
  "Ext.mixin.Mashup": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Queryable": [],
  "Ext.mixin.Responsive": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.panel.Bar": [],
  "Ext.panel.DD": [],
  "Ext.panel.Header": [],
  "Ext.panel.Panel": [
    "Ext.Panel"
  ],
  "Ext.panel.Pinnable": [],
  "Ext.panel.Proxy": [
    "Ext.dd.PanelProxy"
  ],
  "Ext.panel.Table": [],
  "Ext.panel.Title": [],
  "Ext.panel.Tool": [],
  "Ext.perf.Accumulator": [],
  "Ext.perf.Monitor": [
    "Ext.Perf"
  ],
  "Ext.picker.Color": [
    "Ext.ColorPalette"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Month": [
    "Ext.MonthPicker"
  ],
  "Ext.picker.Time": [],
  "Ext.plugin.Abstract": [
    "Ext.AbstractPlugin"
  ],
  "Ext.plugin.AbstractClipboard": [],
  "Ext.plugin.LazyItems": [],
  "Ext.plugin.Manager": [
    "Ext.PluginManager",
    "Ext.PluginMgr"
  ],
  "Ext.plugin.Responsive": [],
  "Ext.plugin.Viewport": [],
  "Ext.resizer.BorderSplitter": [],
  "Ext.resizer.BorderSplitterTracker": [],
  "Ext.resizer.Handle": [],
  "Ext.resizer.ResizeTracker": [],
  "Ext.resizer.Resizer": [
    "Ext.Resizable"
  ],
  "Ext.resizer.Splitter": [],
  "Ext.resizer.SplitterTracker": [],
  "Ext.rtl.Component": [],
  "Ext.rtl.button.Button": [],
  "Ext.rtl.button.Segmented": [],
  "Ext.rtl.dd.DD": [],
  "Ext.rtl.dom.Element": [],
  "Ext.rtl.event.Event": [],
  "Ext.rtl.form.Labelable": [],
  "Ext.rtl.form.field.File": [],
  "Ext.rtl.form.field.FileButton": [],
  "Ext.rtl.grid.CellEditor": [],
  "Ext.rtl.grid.ColumnLayout": [],
  "Ext.rtl.grid.NavigationModel": [],
  "Ext.rtl.grid.column.Column": [],
  "Ext.rtl.grid.plugin.HeaderResizer": [],
  "Ext.rtl.grid.plugin.RowEditing": [],
  "Ext.rtl.layout.ContextItem": [],
  "Ext.rtl.layout.component.Dock": [],
  "Ext.rtl.layout.container.Absolute": [],
  "Ext.rtl.layout.container.Border": [],
  "Ext.rtl.layout.container.Box": [],
  "Ext.rtl.layout.container.Column": [],
  "Ext.rtl.layout.container.HBox": [],
  "Ext.rtl.layout.container.VBox": [],
  "Ext.rtl.layout.container.boxOverflow.Menu": [],
  "Ext.rtl.layout.container.boxOverflow.Scroller": [],
  "Ext.rtl.panel.Bar": [],
  "Ext.rtl.panel.Panel": [],
  "Ext.rtl.panel.Title": [],
  "Ext.rtl.resizer.BorderSplitterTracker": [],
  "Ext.rtl.resizer.ResizeTracker": [],
  "Ext.rtl.resizer.SplitterTracker": [],
  "Ext.rtl.scroll.DomScroller": [],
  "Ext.rtl.scroll.Indicator": [],
  "Ext.rtl.scroll.Scroller": [],
  "Ext.rtl.scroll.TouchScroller": [],
  "Ext.rtl.slider.Multi": [],
  "Ext.rtl.tab.Bar": [],
  "Ext.rtl.tip.QuickTipManager": [],
  "Ext.rtl.tree.Column": [],
  "Ext.rtl.util.FocusableContainer": [],
  "Ext.rtl.util.Renderable": [],
  "Ext.rtl.view.NavigationModel": [],
  "Ext.rtl.view.Table": [],
  "Ext.scroll.DomScroller": [],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.TouchScroller": [],
  "Ext.selection.CellModel": [],
  "Ext.selection.CheckboxModel": [],
  "Ext.selection.DataViewModel": [],
  "Ext.selection.Model": [
    "Ext.AbstractSelectionModel"
  ],
  "Ext.selection.RowModel": [],
  "Ext.selection.TreeModel": [],
  "Ext.slider.Multi": [
    "Ext.slider.MultiSlider"
  ],
  "Ext.slider.Single": [
    "Ext.Slider",
    "Ext.form.SliderField",
    "Ext.slider.SingleSlider",
    "Ext.slider.Slider"
  ],
  "Ext.slider.Thumb": [],
  "Ext.slider.Tip": [],
  "Ext.slider.Widget": [],
  "Ext.sparkline.Bar": [],
  "Ext.sparkline.BarBase": [],
  "Ext.sparkline.Base": [],
  "Ext.sparkline.Box": [],
  "Ext.sparkline.Bullet": [],
  "Ext.sparkline.CanvasBase": [],
  "Ext.sparkline.CanvasCanvas": [],
  "Ext.sparkline.Discrete": [],
  "Ext.sparkline.Line": [],
  "Ext.sparkline.Pie": [],
  "Ext.sparkline.RangeMap": [],
  "Ext.sparkline.Shape": [],
  "Ext.sparkline.TriState": [],
  "Ext.sparkline.VmlCanvas": [],
  "Ext.state.CookieProvider": [],
  "Ext.state.LocalStorageProvider": [],
  "Ext.state.Manager": [],
  "Ext.state.Provider": [],
  "Ext.state.Stateful": [],
  "Ext.tab.Bar": [],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [],
  "Ext.tip.QuickTip": [
    "Ext.QuickTip"
  ],
  "Ext.tip.QuickTipManager": [
    "Ext.QuickTips"
  ],
  "Ext.tip.Tip": [
    "Ext.Tip"
  ],
  "Ext.tip.ToolTip": [
    "Ext.ToolTip"
  ],
  "Ext.toolbar.Breadcrumb": [],
  "Ext.toolbar.Fill": [
    "Ext.Toolbar.Fill"
  ],
  "Ext.toolbar.Item": [
    "Ext.Toolbar.Item"
  ],
  "Ext.toolbar.Paging": [
    "Ext.PagingToolbar"
  ],
  "Ext.toolbar.Separator": [
    "Ext.Toolbar.Separator"
  ],
  "Ext.toolbar.Spacer": [
    "Ext.Toolbar.Spacer"
  ],
  "Ext.toolbar.TextItem": [
    "Ext.Toolbar.TextItem"
  ],
  "Ext.toolbar.Toolbar": [
    "Ext.Toolbar"
  ],
  "Ext.tree.Column": [],
  "Ext.tree.NavigationModel": [],
  "Ext.tree.Panel": [
    "Ext.tree.TreePanel",
    "Ext.TreePanel"
  ],
  "Ext.tree.View": [],
  "Ext.tree.ViewDragZone": [],
  "Ext.tree.ViewDropZone": [],
  "Ext.tree.plugin.TreeViewDragDrop": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Animate": [],
  "Ext.util.Bag": [],
  "Ext.util.Base64": [],
  "Ext.util.CSS": [],
  "Ext.util.CSV": [],
  "Ext.util.ClickRepeater": [],
  "Ext.util.Collection": [],
  "Ext.util.CollectionKey": [],
  "Ext.util.ComponentDragger": [],
  "Ext.util.Cookies": [],
  "Ext.util.DelimitedValue": [],
  "Ext.util.ElementContainer": [],
  "Ext.util.Event": [],
  "Ext.util.Filter": [],
  "Ext.util.FilterCollection": [],
  "Ext.util.Floating": [],
  "Ext.util.FocusTrap": [],
  "Ext.util.Focusable": [],
  "Ext.util.FocusableContainer": [],
  "Ext.util.Format": [],
  "Ext.util.Group": [],
  "Ext.util.GroupCollection": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.History": [
    "Ext.History"
  ],
  "Ext.util.Inflector": [],
  "Ext.util.ItemCollection": [
    "Ext.ItemCollection"
  ],
  "Ext.util.KeyMap": [
    "Ext.KeyMap"
  ],
  "Ext.util.KeyNav": [
    "Ext.KeyNav"
  ],
  "Ext.util.KeyboardInteractive": [],
  "Ext.util.LocalStorage": [],
  "Ext.util.LruCache": [],
  "Ext.util.Memento": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.ObjectTemplate": [],
  "Ext.util.Observable": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.Positionable": [],
  "Ext.util.ProtoElement": [],
  "Ext.util.Queue": [],
  "Ext.util.Region": [],
  "Ext.util.Renderable": [],
  "Ext.util.Schedulable": [],
  "Ext.util.Scheduler": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.SorterCollection": [],
  "Ext.util.StoreHolder": [],
  "Ext.util.TSV": [],
  "Ext.util.TaskManager": [
    "Ext.TaskManager"
  ],
  "Ext.util.TaskRunner": [],
  "Ext.util.TextMetrics": [],
  "Ext.util.Translatable": [],
  "Ext.util.XTemplateCompiler": [],
  "Ext.util.XTemplateParser": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollParent": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.Explorer": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.colorpick.Button": [],
  "Ext.ux.colorpick.ButtonController": [],
  "Ext.ux.colorpick.ColorMap": [],
  "Ext.ux.colorpick.ColorMapController": [],
  "Ext.ux.colorpick.ColorPreview": [],
  "Ext.ux.colorpick.ColorUtils": [],
  "Ext.ux.colorpick.Field": [],
  "Ext.ux.colorpick.Selection": [],
  "Ext.ux.colorpick.Selector": [],
  "Ext.ux.colorpick.SelectorController": [],
  "Ext.ux.colorpick.SelectorModel": [],
  "Ext.ux.colorpick.Slider": [],
  "Ext.ux.colorpick.SliderAlpha": [],
  "Ext.ux.colorpick.SliderController": [],
  "Ext.ux.colorpick.SliderHue": [],
  "Ext.ux.colorpick.SliderSaturation": [],
  "Ext.ux.colorpick.SliderValue": [],
  "Ext.ux.dashboard.GoogleRssPart": [],
  "Ext.ux.dashboard.GoogleRssView": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.desktop.App": [],
  "Ext.ux.desktop.Desktop": [],
  "Ext.ux.desktop.Module": [],
  "Ext.ux.desktop.ShortcutModel": [],
  "Ext.ux.desktop.StartMenu": [],
  "Ext.ux.desktop.TaskBar": [],
  "Ext.ux.desktop.TrayClock": [],
  "Ext.ux.desktop.Video": [],
  "Ext.ux.desktop.Wallpaper": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.google.Api": [],
  "Ext.ux.google.Feeds": [],
  "Ext.ux.grid.SubTable": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.rating.Picker": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.view.AbstractView": [],
  "Ext.view.BoundList": [
    "Ext.BoundList"
  ],
  "Ext.view.BoundListKeyNav": [],
  "Ext.view.DragZone": [],
  "Ext.view.DropZone": [],
  "Ext.view.MultiSelector": [],
  "Ext.view.MultiSelectorSearch": [],
  "Ext.view.NavigationModel": [],
  "Ext.view.NodeCache": [],
  "Ext.view.Table": [
    "Ext.grid.View"
  ],
  "Ext.view.TableLayout": [],
  "Ext.view.View": [
    "Ext.DataView"
  ],
  "Ext.window.MessageBox": [],
  "Ext.window.Toast": [],
  "Ext.window.Window": [
    "Ext.Window"
  ]
});

Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractManager": [],
  "Ext.Action": [],
  "Ext.Ajax": [],
  "Ext.AnimationQueue": [],
  "Ext.Component": [
    "widget.box",
    "widget.component"
  ],
  "Ext.ComponentLoader": [],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Editor": [
    "widget.editor"
  ],
  "Ext.ElementLoader": [],
  "Ext.EventManager": [],
  "Ext.Evented": [],
  "Ext.FocusManager": [],
  "Ext.GlobalEvents": [],
  "Ext.Img": [
    "widget.image",
    "widget.imagecomponent"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Mixin": [],
  "Ext.ProgressBar": [
    "widget.progressbar"
  ],
  "Ext.ProgressBarWidget": [
    "widget.progressbarwidget"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Widget": [
    "widget.widget"
  ],
  "Ext.XTemplate": [],
  "Ext.ZIndexManager": [],
  "Ext.app.Application": [],
  "Ext.app.BaseController": [],
  "Ext.app.Controller": [],
  "Ext.app.EventBus": [],
  "Ext.app.EventDomain": [],
  "Ext.app.Profile": [],
  "Ext.app.Util": [],
  "Ext.app.ViewController": [],
  "Ext.app.ViewModel": [
    "viewmodel.default"
  ],
  "Ext.app.bind.AbstractStub": [],
  "Ext.app.bind.BaseBinding": [],
  "Ext.app.bind.Binding": [],
  "Ext.app.bind.Formula": [],
  "Ext.app.bind.LinkStub": [],
  "Ext.app.bind.Multi": [],
  "Ext.app.bind.RootStub": [],
  "Ext.app.bind.Stub": [],
  "Ext.app.bind.Template": [],
  "Ext.app.bind.TemplateBinding": [],
  "Ext.app.bindinspector.ComponentDetail": [
    "widget.bindinspector-componentdetail"
  ],
  "Ext.app.bindinspector.ComponentList": [
    "widget.bindinspector-componentlist"
  ],
  "Ext.app.bindinspector.Container": [
    "widget.bindinspector-container"
  ],
  "Ext.app.bindinspector.Environment": [],
  "Ext.app.bindinspector.Inspector": [],
  "Ext.app.bindinspector.Util": [],
  "Ext.app.bindinspector.ViewModelDetail": [
    "widget.bindinspector-viewmodeldetail"
  ],
  "Ext.app.bindinspector.noconflict.BaseModel": [],
  "Ext.app.domain.Component": [],
  "Ext.app.domain.Controller": [],
  "Ext.app.domain.Direct": [],
  "Ext.app.domain.Global": [],
  "Ext.app.domain.Store": [],
  "Ext.app.domain.View": [],
  "Ext.app.route.Queue": [],
  "Ext.app.route.Route": [],
  "Ext.app.route.Router": [],
  "Ext.button.Button": [
    "widget.button"
  ],
  "Ext.button.Cycle": [
    "widget.cycle"
  ],
  "Ext.button.Manager": [],
  "Ext.button.Segmented": [
    "widget.segmentedbutton"
  ],
  "Ext.button.Split": [
    "widget.splitbutton"
  ],
  "Ext.chart.AbstractChart": [],
  "Ext.chart.CartesianChart": [
    "widget.cartesian",
    "widget.chart"
  ],
  "Ext.chart.Legend": [
    "widget.legend"
  ],
  "Ext.chart.LegendBase": [],
  "Ext.chart.MarkerHolder": [],
  "Ext.chart.Markers": [],
  "Ext.chart.PolarChart": [
    "widget.polar"
  ],
  "Ext.chart.SpaceFillingChart": [
    "widget.spacefilling"
  ],
  "Ext.chart.TipSurface": [],
  "Ext.chart.axis.Axis": [
    "widget.axis"
  ],
  "Ext.chart.axis.Axis3D": [
    "widget.axis3d"
  ],
  "Ext.chart.axis.Category": [
    "axis.category"
  ],
  "Ext.chart.axis.Category3D": [
    "axis.category3d"
  ],
  "Ext.chart.axis.Numeric": [
    "axis.numeric",
    "axis.radial"
  ],
  "Ext.chart.axis.Numeric3D": [
    "axis.numeric3d"
  ],
  "Ext.chart.axis.Time": [
    "axis.time"
  ],
  "Ext.chart.axis.Time3D": [
    "axis.time3d"
  ],
  "Ext.chart.axis.layout.CombineDuplicate": [
    "axisLayout.combineDuplicate"
  ],
  "Ext.chart.axis.layout.Continuous": [
    "axisLayout.continuous"
  ],
  "Ext.chart.axis.layout.Discrete": [
    "axisLayout.discrete"
  ],
  "Ext.chart.axis.layout.Layout": [],
  "Ext.chart.axis.segmenter.Names": [
    "segmenter.names"
  ],
  "Ext.chart.axis.segmenter.Numeric": [
    "segmenter.numeric"
  ],
  "Ext.chart.axis.segmenter.Segmenter": [],
  "Ext.chart.axis.segmenter.Time": [
    "segmenter.time"
  ],
  "Ext.chart.axis.sprite.Axis": [
    "sprite.axis"
  ],
  "Ext.chart.axis.sprite.Axis3D": [
    "sprite.axis3d"
  ],
  "Ext.chart.grid.CircularGrid": [
    "grid.circular"
  ],
  "Ext.chart.grid.HorizontalGrid": [
    "grid.horizontal"
  ],
  "Ext.chart.grid.HorizontalGrid3D": [
    "grid.horizontal3d"
  ],
  "Ext.chart.grid.RadialGrid": [
    "grid.radial"
  ],
  "Ext.chart.grid.VerticalGrid": [
    "grid.vertical"
  ],
  "Ext.chart.grid.VerticalGrid3D": [
    "grid.vertical3d"
  ],
  "Ext.chart.interactions.Abstract": [
    "widget.interaction"
  ],
  "Ext.chart.interactions.CrossZoom": [
    "interaction.crosszoom"
  ],
  "Ext.chart.interactions.Crosshair": [
    "interaction.crosshair"
  ],
  "Ext.chart.interactions.ItemEdit": [
    "interaction.itemedit"
  ],
  "Ext.chart.interactions.ItemHighlight": [
    "interaction.itemhighlight"
  ],
  "Ext.chart.interactions.ItemInfo": [
    "interaction.iteminfo"
  ],
  "Ext.chart.interactions.PanZoom": [
    "interaction.panzoom"
  ],
  "Ext.chart.interactions.Rotate": [
    "interaction.rotate"
  ],
  "Ext.chart.interactions.RotatePie3D": [
    "interaction.rotatePie3d"
  ],
  "Ext.chart.label.Callout": [],
  "Ext.chart.label.Label": [],
  "Ext.chart.plugin.ItemEvents": [
    "plugin.chartitemevents"
  ],
  "Ext.chart.series.Area": [
    "series.area"
  ],
  "Ext.chart.series.Bar": [
    "series.bar"
  ],
  "Ext.chart.series.Bar3D": [
    "series.bar3d"
  ],
  "Ext.chart.series.CandleStick": [
    "series.candlestick"
  ],
  "Ext.chart.series.Cartesian": [],
  "Ext.chart.series.Gauge": [
    "series.gauge"
  ],
  "Ext.chart.series.Line": [
    "series.line"
  ],
  "Ext.chart.series.Pie": [
    "series.pie"
  ],
  "Ext.chart.series.Pie3D": [
    "series.pie3d"
  ],
  "Ext.chart.series.Polar": [],
  "Ext.chart.series.Radar": [
    "series.radar"
  ],
  "Ext.chart.series.Scatter": [
    "series.scatter"
  ],
  "Ext.chart.series.Series": [],
  "Ext.chart.series.StackedCartesian": [],
  "Ext.chart.series.sprite.Aggregative": [],
  "Ext.chart.series.sprite.Area": [
    "sprite.areaSeries"
  ],
  "Ext.chart.series.sprite.Bar": [
    "sprite.barSeries"
  ],
  "Ext.chart.series.sprite.Bar3D": [
    "sprite.bar3dSeries"
  ],
  "Ext.chart.series.sprite.Box": [
    "sprite.box"
  ],
  "Ext.chart.series.sprite.CandleStick": [
    "sprite.candlestickSeries"
  ],
  "Ext.chart.series.sprite.Cartesian": [],
  "Ext.chart.series.sprite.Line": [
    "sprite.lineSeries"
  ],
  "Ext.chart.series.sprite.Pie3DPart": [
    "sprite.pie3dPart"
  ],
  "Ext.chart.series.sprite.PieSlice": [
    "sprite.pieslice"
  ],
  "Ext.chart.series.sprite.Polar": [],
  "Ext.chart.series.sprite.Radar": [
    "sprite.radar"
  ],
  "Ext.chart.series.sprite.Scatter": [
    "sprite.scatterSeries"
  ],
  "Ext.chart.series.sprite.Series": [],
  "Ext.chart.series.sprite.StackedCartesian": [],
  "Ext.chart.theme.Base": [],
  "Ext.chart.theme.Blue": [
    "chart.theme.Blue",
    "chart.theme.blue"
  ],
  "Ext.chart.theme.BlueGradients": [
    "chart.theme.Blue:gradients",
    "chart.theme.blue-gradients"
  ],
  "Ext.chart.theme.Category1": [
    "chart.theme.Category1",
    "chart.theme.category1"
  ],
  "Ext.chart.theme.Category1Gradients": [
    "chart.theme.Category1:gradients",
    "chart.theme.category1-gradients"
  ],
  "Ext.chart.theme.Category2": [
    "chart.theme.Category2",
    "chart.theme.category2"
  ],
  "Ext.chart.theme.Category2Gradients": [
    "chart.theme.Category2:gradients",
    "chart.theme.category2-gradients"
  ],
  "Ext.chart.theme.Category3": [
    "chart.theme.Category3",
    "chart.theme.category3"
  ],
  "Ext.chart.theme.Category3Gradients": [
    "chart.theme.Category3:gradients",
    "chart.theme.category3-gradients"
  ],
  "Ext.chart.theme.Category4": [
    "chart.theme.Category4",
    "chart.theme.category4"
  ],
  "Ext.chart.theme.Category4Gradients": [
    "chart.theme.Category4:gradients",
    "chart.theme.category4-gradients"
  ],
  "Ext.chart.theme.Category5": [
    "chart.theme.Category5",
    "chart.theme.category5"
  ],
  "Ext.chart.theme.Category5Gradients": [
    "chart.theme.Category5:gradients",
    "chart.theme.category5-gradients"
  ],
  "Ext.chart.theme.Category6": [
    "chart.theme.Category6",
    "chart.theme.category6"
  ],
  "Ext.chart.theme.Category6Gradients": [
    "chart.theme.Category6:gradients",
    "chart.theme.category6-gradients"
  ],
  "Ext.chart.theme.Default": [
    "chart.theme.Base",
    "chart.theme.default"
  ],
  "Ext.chart.theme.DefaultGradients": [
    "chart.theme.Base:gradients",
    "chart.theme.default-gradients"
  ],
  "Ext.chart.theme.Green": [
    "chart.theme.Green",
    "chart.theme.green"
  ],
  "Ext.chart.theme.GreenGradients": [
    "chart.theme.Green:gradients",
    "chart.theme.green-gradients"
  ],
  "Ext.chart.theme.Midnight": [
    "chart.theme.Midnight",
    "chart.theme.midnight"
  ],
  "Ext.chart.theme.Muted": [
    "chart.theme.Muted",
    "chart.theme.muted"
  ],
  "Ext.chart.theme.Purple": [
    "chart.theme.Purple",
    "chart.theme.purple"
  ],
  "Ext.chart.theme.PurpleGradients": [
    "chart.theme.Purple:gradients",
    "chart.theme.purple-gradients"
  ],
  "Ext.chart.theme.Red": [
    "chart.theme.Red",
    "chart.theme.red"
  ],
  "Ext.chart.theme.RedGradients": [
    "chart.theme.Red:gradients",
    "chart.theme.red-gradients"
  ],
  "Ext.chart.theme.Sky": [
    "chart.theme.Sky",
    "chart.theme.sky"
  ],
  "Ext.chart.theme.SkyGradients": [
    "chart.theme.Sky:gradients",
    "chart.theme.sky-gradients"
  ],
  "Ext.chart.theme.Yellow": [
    "chart.theme.Yellow",
    "chart.theme.yellow"
  ],
  "Ext.chart.theme.YellowGradients": [
    "chart.theme.Yellow:gradients",
    "chart.theme.yellow-gradients"
  ],
  "Ext.container.ButtonGroup": [
    "widget.buttongroup"
  ],
  "Ext.container.Container": [
    "widget.container"
  ],
  "Ext.container.DockingContainer": [],
  "Ext.container.Monitor": [],
  "Ext.container.Viewport": [
    "widget.viewport"
  ],
  "Ext.dashboard.Column": [
    "widget.dashboard-column"
  ],
  "Ext.dashboard.Dashboard": [
    "widget.dashboard"
  ],
  "Ext.dashboard.DropZone": [],
  "Ext.dashboard.Panel": [
    "widget.dashboard-panel"
  ],
  "Ext.dashboard.Part": [
    "part.part"
  ],
  "Ext.data.AbstractStore": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.BufferedStore": [
    "store.buffered"
  ],
  "Ext.data.ChainedStore": [
    "store.chained"
  ],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.ErrorCollection": [],
  "Ext.data.JsonP": [],
  "Ext.data.JsonPStore": [
    "store.jsonp"
  ],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.LocalStore": [],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.PageMap": [],
  "Ext.data.ProxyStore": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.Session": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeModel": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validation": [],
  "Ext.data.XmlStore": [
    "store.xml"
  ],
  "Ext.data.field.Boolean": [
    "data.field.bool",
    "data.field.boolean"
  ],
  "Ext.data.field.Date": [
    "data.field.date"
  ],
  "Ext.data.field.Field": [
    "data.field.auto"
  ],
  "Ext.data.field.Integer": [
    "data.field.int",
    "data.field.integer"
  ],
  "Ext.data.field.Number": [
    "data.field.float",
    "data.field.number"
  ],
  "Ext.data.field.String": [
    "data.field.string"
  ],
  "Ext.data.flash.BinaryXhr": [],
  "Ext.data.identifier.Generator": [
    "data.identifier.default"
  ],
  "Ext.data.identifier.Negative": [
    "data.identifier.negative"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.matrix.Matrix": [],
  "Ext.data.matrix.Side": [],
  "Ext.data.matrix.Slice": [],
  "Ext.data.operation.Create": [
    "data.operation.create"
  ],
  "Ext.data.operation.Destroy": [
    "data.operation.destroy"
  ],
  "Ext.data.operation.Operation": [],
  "Ext.data.operation.Read": [
    "data.operation.read"
  ],
  "Ext.data.operation.Update": [
    "data.operation.update"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [
    "reader.base"
  ],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.schema.Association": [],
  "Ext.data.schema.ManyToMany": [],
  "Ext.data.schema.ManyToOne": [],
  "Ext.data.schema.Namer": [
    "namer.default"
  ],
  "Ext.data.schema.OneToOne": [],
  "Ext.data.schema.Role": [],
  "Ext.data.schema.Schema": [
    "schema.default"
  ],
  "Ext.data.session.BatchVisitor": [],
  "Ext.data.session.ChangesVisitor": [],
  "Ext.data.session.ChildChangesVisitor": [],
  "Ext.data.validator.Bound": [
    "data.validator.bound"
  ],
  "Ext.data.validator.Email": [
    "data.validator.email"
  ],
  "Ext.data.validator.Exclusion": [
    "data.validator.exclusion"
  ],
  "Ext.data.validator.Format": [
    "data.validator.format"
  ],
  "Ext.data.validator.Inclusion": [
    "data.validator.inclusion"
  ],
  "Ext.data.validator.Length": [
    "data.validator.length"
  ],
  "Ext.data.validator.List": [
    "data.validator.list"
  ],
  "Ext.data.validator.Presence": [
    "data.validator.presence"
  ],
  "Ext.data.validator.Range": [
    "data.validator.range"
  ],
  "Ext.data.validator.Validator": [
    "data.validator.base"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dd.DD": [],
  "Ext.dd.DDProxy": [],
  "Ext.dd.DDTarget": [],
  "Ext.dd.DragDrop": [],
  "Ext.dd.DragDropManager": [],
  "Ext.dd.DragSource": [],
  "Ext.dd.DragTracker": [],
  "Ext.dd.DragZone": [],
  "Ext.dd.DropTarget": [],
  "Ext.dd.DropZone": [],
  "Ext.dd.Registry": [],
  "Ext.dd.ScrollManager": [],
  "Ext.dd.StatusProxy": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.ButtonElement": [],
  "Ext.dom.CompositeElement": [],
  "Ext.dom.CompositeElementLite": [],
  "Ext.dom.Element": [],
  "Ext.dom.ElementEvent": [],
  "Ext.dom.Fly": [],
  "Ext.dom.GarbageCollector": [],
  "Ext.dom.Helper": [],
  "Ext.dom.Layer": [],
  "Ext.dom.Query": [],
  "Ext.dom.Shadow": [],
  "Ext.dom.Shim": [],
  "Ext.dom.Underlay": [],
  "Ext.dom.UnderlayPool": [],
  "Ext.draw.Animator": [],
  "Ext.draw.Color": [],
  "Ext.draw.Container": [
    "widget.draw"
  ],
  "Ext.draw.ContainerBase": [],
  "Ext.draw.Draw": [],
  "Ext.draw.LimitedCache": [],
  "Ext.draw.Matrix": [],
  "Ext.draw.Path": [],
  "Ext.draw.PathUtil": [],
  "Ext.draw.Point": [],
  "Ext.draw.SegmentTree": [],
  "Ext.draw.Surface": [
    "widget.surface"
  ],
  "Ext.draw.SurfaceBase": [],
  "Ext.draw.TextMeasurer": [],
  "Ext.draw.TimingFunctions": [],
  "Ext.draw.engine.Canvas": [],
  "Ext.draw.engine.Svg": [],
  "Ext.draw.engine.SvgContext": [],
  "Ext.draw.engine.SvgContext.Gradient": [],
  "Ext.draw.gradient.Gradient": [],
  "Ext.draw.gradient.GradientDefinition": [],
  "Ext.draw.gradient.Linear": [],
  "Ext.draw.gradient.Radial": [],
  "Ext.draw.modifier.Animation": [
    "modifier.animation"
  ],
  "Ext.draw.modifier.Highlight": [
    "modifier.highlight"
  ],
  "Ext.draw.modifier.Modifier": [],
  "Ext.draw.modifier.Target": [
    "modifier.target"
  ],
  "Ext.draw.overrides.Path": [],
  "Ext.draw.overrides.Surface": [],
  "Ext.draw.overrides.sprite.Path": [],
  "Ext.draw.plugin.SpriteEvents": [
    "plugin.spriteevents"
  ],
  "Ext.draw.sprite.AnimationParser": [],
  "Ext.draw.sprite.Arc": [
    "sprite.arc"
  ],
  "Ext.draw.sprite.Arrow": [
    "sprite.arrow"
  ],
  "Ext.draw.sprite.AttributeDefinition": [],
  "Ext.draw.sprite.AttributeParser": [],
  "Ext.draw.sprite.Circle": [
    "sprite.circle"
  ],
  "Ext.draw.sprite.Composite": [
    "sprite.composite"
  ],
  "Ext.draw.sprite.Cross": [
    "sprite.cross"
  ],
  "Ext.draw.sprite.Diamond": [
    "sprite.diamond"
  ],
  "Ext.draw.sprite.Ellipse": [
    "sprite.ellipse"
  ],
  "Ext.draw.sprite.EllipticalArc": [
    "sprite.ellipticalArc"
  ],
  "Ext.draw.sprite.Image": [
    "sprite.image"
  ],
  "Ext.draw.sprite.Instancing": [
    "sprite.instancing"
  ],
  "Ext.draw.sprite.Line": [
    "sprite.line"
  ],
  "Ext.draw.sprite.Path": [
    "Ext.draw.Sprite",
    "sprite.path"
  ],
  "Ext.draw.sprite.Plus": [
    "sprite.plus"
  ],
  "Ext.draw.sprite.Rect": [
    "sprite.rect"
  ],
  "Ext.draw.sprite.Sector": [
    "sprite.sector"
  ],
  "Ext.draw.sprite.Sprite": [
    "sprite.sprite"
  ],
  "Ext.draw.sprite.Square": [
    "sprite.square"
  ],
  "Ext.draw.sprite.Text": [
    "sprite.text"
  ],
  "Ext.draw.sprite.Tick": [
    "sprite.tick"
  ],
  "Ext.draw.sprite.Triangle": [
    "sprite.triangle"
  ],
  "Ext.event.Event": [],
  "Ext.event.gesture.DoubleTap": [],
  "Ext.event.gesture.Drag": [],
  "Ext.event.gesture.EdgeSwipe": [],
  "Ext.event.gesture.LongPress": [],
  "Ext.event.gesture.MultiTouch": [],
  "Ext.event.gesture.Pinch": [],
  "Ext.event.gesture.Recognizer": [],
  "Ext.event.gesture.Rotate": [],
  "Ext.event.gesture.SingleTouch": [],
  "Ext.event.gesture.Swipe": [],
  "Ext.event.gesture.Tap": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Focus": [],
  "Ext.event.publisher.Gesture": [],
  "Ext.event.publisher.MouseEnterLeave": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.flash.Component": [
    "widget.flash"
  ],
  "Ext.form.Basic": [],
  "Ext.form.CheckboxGroup": [
    "widget.checkboxgroup"
  ],
  "Ext.form.CheckboxManager": [],
  "Ext.form.FieldAncestor": [],
  "Ext.form.FieldContainer": [
    "widget.fieldcontainer"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Label": [
    "widget.label"
  ],
  "Ext.form.Labelable": [],
  "Ext.form.Panel": [
    "widget.form"
  ],
  "Ext.form.RadioGroup": [
    "widget.radiogroup"
  ],
  "Ext.form.RadioManager": [],
  "Ext.form.action.Action": [],
  "Ext.form.action.DirectAction": [],
  "Ext.form.action.DirectLoad": [
    "formaction.directload"
  ],
  "Ext.form.action.DirectSubmit": [
    "formaction.directsubmit"
  ],
  "Ext.form.action.Load": [
    "formaction.load"
  ],
  "Ext.form.action.StandardSubmit": [
    "formaction.standardsubmit"
  ],
  "Ext.form.action.Submit": [
    "formaction.submit"
  ],
  "Ext.form.field.Base": [
    "widget.field"
  ],
  "Ext.form.field.Checkbox": [
    "widget.checkbox",
    "widget.checkboxfield"
  ],
  "Ext.form.field.ComboBox": [
    "widget.combo",
    "widget.combobox"
  ],
  "Ext.form.field.Date": [
    "widget.datefield"
  ],
  "Ext.form.field.Display": [
    "widget.displayfield"
  ],
  "Ext.form.field.Field": [],
  "Ext.form.field.File": [
    "widget.filefield",
    "widget.fileuploadfield"
  ],
  "Ext.form.field.FileButton": [
    "widget.filebutton"
  ],
  "Ext.form.field.Hidden": [
    "widget.hidden",
    "widget.hiddenfield"
  ],
  "Ext.form.field.HtmlEditor": [
    "widget.htmleditor"
  ],
  "Ext.form.field.Number": [
    "widget.numberfield"
  ],
  "Ext.form.field.Picker": [
    "widget.pickerfield"
  ],
  "Ext.form.field.Radio": [
    "widget.radio",
    "widget.radiofield"
  ],
  "Ext.form.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.form.field.Tag": [
    "widget.tagfield"
  ],
  "Ext.form.field.Text": [
    "widget.textfield"
  ],
  "Ext.form.field.TextArea": [
    "widget.textarea",
    "widget.textareafield"
  ],
  "Ext.form.field.Time": [
    "widget.timefield"
  ],
  "Ext.form.field.Trigger": [
    "widget.trigger",
    "widget.triggerfield"
  ],
  "Ext.form.field.VTypes": [],
  "Ext.form.trigger.Component": [
    "trigger.component"
  ],
  "Ext.form.trigger.Spinner": [
    "trigger.spinner"
  ],
  "Ext.form.trigger.Trigger": [
    "trigger.trigger"
  ],
  "Ext.fx.Anim": [],
  "Ext.fx.Animation": [],
  "Ext.fx.Animator": [],
  "Ext.fx.CubicBezier": [],
  "Ext.fx.DrawPath": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Manager": [],
  "Ext.fx.PropertyHandler": [],
  "Ext.fx.Queue": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Easing": [],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.fx.target.Component": [],
  "Ext.fx.target.CompositeElement": [],
  "Ext.fx.target.CompositeElementCSS": [],
  "Ext.fx.target.CompositeSprite": [],
  "Ext.fx.target.Element": [],
  "Ext.fx.target.ElementCSS": [],
  "Ext.fx.target.Sprite": [],
  "Ext.fx.target.Target": [],
  "Ext.grid.CellContext": [],
  "Ext.grid.CellEditor": [],
  "Ext.grid.ColumnComponentLayout": [
    "layout.columncomponent"
  ],
  "Ext.grid.ColumnLayout": [
    "layout.gridcolumn"
  ],
  "Ext.grid.ColumnManager": [],
  "Ext.grid.NavigationModel": [
    "view.navigation.grid"
  ],
  "Ext.grid.Panel": [
    "widget.grid",
    "widget.gridpanel"
  ],
  "Ext.grid.RowEditor": [
    "widget.roweditor"
  ],
  "Ext.grid.RowEditorButtons": [
    "widget.roweditorbuttons"
  ],
  "Ext.grid.Scroller": [],
  "Ext.grid.ViewDropZone": [],
  "Ext.grid.column.Action": [
    "widget.actioncolumn"
  ],
  "Ext.grid.column.Boolean": [
    "widget.booleancolumn"
  ],
  "Ext.grid.column.Check": [
    "widget.checkcolumn"
  ],
  "Ext.grid.column.Column": [
    "widget.gridcolumn"
  ],
  "Ext.grid.column.Date": [
    "widget.datecolumn"
  ],
  "Ext.grid.column.Number": [
    "widget.numbercolumn"
  ],
  "Ext.grid.column.RowNumberer": [
    "widget.rownumberer"
  ],
  "Ext.grid.column.Template": [
    "widget.templatecolumn"
  ],
  "Ext.grid.column.Widget": [
    "widget.widgetcolumn"
  ],
  "Ext.grid.feature.AbstractSummary": [
    "feature.abstractsummary"
  ],
  "Ext.grid.feature.Feature": [
    "feature.feature"
  ],
  "Ext.grid.feature.GroupStore": [],
  "Ext.grid.feature.Grouping": [
    "feature.grouping"
  ],
  "Ext.grid.feature.GroupingSummary": [
    "feature.groupingsummary"
  ],
  "Ext.grid.feature.RowBody": [
    "feature.rowbody"
  ],
  "Ext.grid.feature.Summary": [
    "feature.summary"
  ],
  "Ext.grid.filters.Filters": [
    "plugin.gridfilters"
  ],
  "Ext.grid.filters.filter.Base": [],
  "Ext.grid.filters.filter.Boolean": [
    "grid.filter.boolean"
  ],
  "Ext.grid.filters.filter.Date": [
    "grid.filter.date"
  ],
  "Ext.grid.filters.filter.List": [
    "grid.filter.list"
  ],
  "Ext.grid.filters.filter.Number": [
    "grid.filter.number",
    "grid.filter.numeric"
  ],
  "Ext.grid.filters.filter.SingleFilter": [],
  "Ext.grid.filters.filter.String": [
    "grid.filter.string"
  ],
  "Ext.grid.filters.filter.TriFilter": [],
  "Ext.grid.header.Container": [
    "widget.headercontainer"
  ],
  "Ext.grid.header.DragZone": [],
  "Ext.grid.header.DropZone": [],
  "Ext.grid.locking.HeaderContainer": [],
  "Ext.grid.locking.Lockable": [],
  "Ext.grid.locking.RowSynchronizer": [],
  "Ext.grid.locking.View": [],
  "Ext.grid.plugin.BufferedRenderer": [
    "plugin.bufferedrenderer"
  ],
  "Ext.grid.plugin.CellEditing": [
    "plugin.cellediting"
  ],
  "Ext.grid.plugin.Clipboard": [
    "plugin.clipboard"
  ],
  "Ext.grid.plugin.DragDrop": [
    "plugin.gridviewdragdrop"
  ],
  "Ext.grid.plugin.Editing": [
    "editing.editing"
  ],
  "Ext.grid.plugin.HeaderReorderer": [
    "plugin.gridheaderreorderer"
  ],
  "Ext.grid.plugin.HeaderResizer": [
    "plugin.gridheaderresizer"
  ],
  "Ext.grid.plugin.RowEditing": [
    "plugin.rowediting"
  ],
  "Ext.grid.plugin.RowExpander": [
    "plugin.rowexpander"
  ],
  "Ext.grid.property.Grid": [
    "widget.propertygrid"
  ],
  "Ext.grid.property.HeaderContainer": [],
  "Ext.grid.property.Property": [],
  "Ext.grid.property.Reader": [],
  "Ext.grid.property.Store": [],
  "Ext.grid.selection.Cells": [],
  "Ext.grid.selection.Columns": [],
  "Ext.grid.selection.Replicator": [
    "plugin.selectionreplicator"
  ],
  "Ext.grid.selection.Rows": [],
  "Ext.grid.selection.Selection": [],
  "Ext.grid.selection.SelectionExtender": [],
  "Ext.grid.selection.SpreadsheetModel": [
    "selection.spreadsheet"
  ],
  "Ext.layout.Context": [],
  "Ext.layout.ContextItem": [],
  "Ext.layout.Layout": [],
  "Ext.layout.SizeModel": [],
  "Ext.layout.component.Auto": [
    "layout.autocomponent"
  ],
  "Ext.layout.component.Body": [
    "layout.body"
  ],
  "Ext.layout.component.BoundList": [
    "layout.boundlist"
  ],
  "Ext.layout.component.Component": [],
  "Ext.layout.component.Dock": [
    "layout.dock"
  ],
  "Ext.layout.component.FieldSet": [
    "layout.fieldset"
  ],
  "Ext.layout.component.ProgressBar": [
    "layout.progressbar"
  ],
  "Ext.layout.component.field.FieldContainer": [
    "layout.fieldcontainer"
  ],
  "Ext.layout.component.field.HtmlEditor": [
    "layout.htmleditor"
  ],
  "Ext.layout.container.Absolute": [
    "layout.absolute"
  ],
  "Ext.layout.container.Accordion": [
    "layout.accordion"
  ],
  "Ext.layout.container.Anchor": [
    "layout.anchor"
  ],
  "Ext.layout.container.Auto": [
    "layout.auto",
    "layout.autocontainer"
  ],
  "Ext.layout.container.Border": [
    "layout.border"
  ],
  "Ext.layout.container.Box": [
    "layout.box"
  ],
  "Ext.layout.container.Card": [
    "layout.card"
  ],
  "Ext.layout.container.Center": [
    "layout.center",
    "layout.ux.center"
  ],
  "Ext.layout.container.CheckboxGroup": [
    "layout.checkboxgroup"
  ],
  "Ext.layout.container.Column": [
    "layout.column"
  ],
  "Ext.layout.container.ColumnSplitter": [
    "widget.columnsplitter"
  ],
  "Ext.layout.container.ColumnSplitterTracker": [],
  "Ext.layout.container.Container": [
    "layout.container"
  ],
  "Ext.layout.container.Dashboard": [
    "layout.dashboard"
  ],
  "Ext.layout.container.Editor": [
    "layout.editor"
  ],
  "Ext.layout.container.Fit": [
    "layout.fit"
  ],
  "Ext.layout.container.Form": [
    "layout.form"
  ],
  "Ext.layout.container.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.container.SegmentedButton": [
    "layout.segmentedbutton"
  ],
  "Ext.layout.container.Table": [
    "layout.table"
  ],
  "Ext.layout.container.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.container.border.Region": [],
  "Ext.layout.container.boxOverflow.Menu": [
    "box.overflow.Menu",
    "box.overflow.menu"
  ],
  "Ext.layout.container.boxOverflow.None": [
    "box.overflow.None",
    "box.overflow.none"
  ],
  "Ext.layout.container.boxOverflow.Scroller": [
    "box.overflow.Scroller",
    "box.overflow.scroller"
  ],
  "Ext.menu.CheckItem": [
    "widget.menucheckitem"
  ],
  "Ext.menu.ColorPicker": [
    "widget.colormenu"
  ],
  "Ext.menu.DatePicker": [
    "widget.datemenu"
  ],
  "Ext.menu.Item": [
    "widget.menuitem"
  ],
  "Ext.menu.Manager": [],
  "Ext.menu.Menu": [
    "widget.menu"
  ],
  "Ext.menu.Separator": [
    "widget.menuseparator"
  ],
  "Ext.mixin.Accessible": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.ComponentDelegation": [],
  "Ext.mixin.Container": [],
  "Ext.mixin.Factoryable": [],
  "Ext.mixin.Hookable": [],
  "Ext.mixin.Identifiable": [],
  "Ext.mixin.Inheritable": [],
  "Ext.mixin.Mashup": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Queryable": [],
  "Ext.mixin.Responsive": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.panel.Bar": [],
  "Ext.panel.DD": [],
  "Ext.panel.Header": [
    "widget.header"
  ],
  "Ext.panel.Panel": [
    "widget.panel"
  ],
  "Ext.panel.Pinnable": [],
  "Ext.panel.Proxy": [],
  "Ext.panel.Table": [
    "widget.tablepanel"
  ],
  "Ext.panel.Title": [
    "widget.title"
  ],
  "Ext.panel.Tool": [
    "widget.tool"
  ],
  "Ext.perf.Accumulator": [],
  "Ext.perf.Monitor": [],
  "Ext.picker.Color": [
    "widget.colorpicker"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Month": [
    "widget.monthpicker"
  ],
  "Ext.picker.Time": [
    "widget.timepicker"
  ],
  "Ext.plugin.Abstract": [],
  "Ext.plugin.AbstractClipboard": [],
  "Ext.plugin.LazyItems": [
    "plugin.lazyitems"
  ],
  "Ext.plugin.Manager": [],
  "Ext.plugin.Responsive": [
    "plugin.responsive"
  ],
  "Ext.plugin.Viewport": [
    "plugin.viewport"
  ],
  "Ext.resizer.BorderSplitter": [
    "widget.bordersplitter"
  ],
  "Ext.resizer.BorderSplitterTracker": [],
  "Ext.resizer.Handle": [],
  "Ext.resizer.ResizeTracker": [],
  "Ext.resizer.Resizer": [],
  "Ext.resizer.Splitter": [
    "widget.splitter"
  ],
  "Ext.resizer.SplitterTracker": [],
  "Ext.rtl.Component": [],
  "Ext.rtl.button.Button": [],
  "Ext.rtl.button.Segmented": [],
  "Ext.rtl.dd.DD": [],
  "Ext.rtl.dom.Element": [],
  "Ext.rtl.event.Event": [],
  "Ext.rtl.form.Labelable": [],
  "Ext.rtl.form.field.File": [],
  "Ext.rtl.form.field.FileButton": [],
  "Ext.rtl.grid.CellEditor": [],
  "Ext.rtl.grid.ColumnLayout": [],
  "Ext.rtl.grid.NavigationModel": [],
  "Ext.rtl.grid.column.Column": [],
  "Ext.rtl.grid.plugin.HeaderResizer": [],
  "Ext.rtl.grid.plugin.RowEditing": [],
  "Ext.rtl.layout.ContextItem": [],
  "Ext.rtl.layout.component.Dock": [],
  "Ext.rtl.layout.container.Absolute": [],
  "Ext.rtl.layout.container.Border": [],
  "Ext.rtl.layout.container.Box": [],
  "Ext.rtl.layout.container.Column": [],
  "Ext.rtl.layout.container.HBox": [],
  "Ext.rtl.layout.container.VBox": [],
  "Ext.rtl.layout.container.boxOverflow.Menu": [],
  "Ext.rtl.layout.container.boxOverflow.Scroller": [],
  "Ext.rtl.panel.Bar": [],
  "Ext.rtl.panel.Panel": [],
  "Ext.rtl.panel.Title": [],
  "Ext.rtl.resizer.BorderSplitterTracker": [],
  "Ext.rtl.resizer.ResizeTracker": [],
  "Ext.rtl.resizer.SplitterTracker": [],
  "Ext.rtl.scroll.DomScroller": [],
  "Ext.rtl.scroll.Indicator": [],
  "Ext.rtl.scroll.Scroller": [],
  "Ext.rtl.scroll.TouchScroller": [],
  "Ext.rtl.slider.Multi": [],
  "Ext.rtl.tab.Bar": [],
  "Ext.rtl.tip.QuickTipManager": [],
  "Ext.rtl.tree.Column": [],
  "Ext.rtl.util.FocusableContainer": [],
  "Ext.rtl.util.Renderable": [],
  "Ext.rtl.view.NavigationModel": [],
  "Ext.rtl.view.Table": [],
  "Ext.scroll.DomScroller": [
    "scroller.dom"
  ],
  "Ext.scroll.Indicator": [
    "widget.scrollindicator"
  ],
  "Ext.scroll.Scroller": [
    "scroller.scroller"
  ],
  "Ext.scroll.TouchScroller": [
    "scroller.touch"
  ],
  "Ext.selection.CellModel": [
    "selection.cellmodel"
  ],
  "Ext.selection.CheckboxModel": [
    "selection.checkboxmodel"
  ],
  "Ext.selection.DataViewModel": [
    "selection.dataviewmodel"
  ],
  "Ext.selection.Model": [
    "selection.abstract"
  ],
  "Ext.selection.RowModel": [
    "selection.rowmodel"
  ],
  "Ext.selection.TreeModel": [
    "selection.treemodel"
  ],
  "Ext.slider.Multi": [
    "widget.multislider"
  ],
  "Ext.slider.Single": [
    "widget.slider",
    "widget.sliderfield"
  ],
  "Ext.slider.Thumb": [],
  "Ext.slider.Tip": [
    "widget.slidertip"
  ],
  "Ext.slider.Widget": [
    "widget.sliderwidget"
  ],
  "Ext.sparkline.Bar": [
    "widget.sparklinebar"
  ],
  "Ext.sparkline.BarBase": [],
  "Ext.sparkline.Base": [],
  "Ext.sparkline.Box": [
    "widget.sparklinebox"
  ],
  "Ext.sparkline.Bullet": [
    "widget.sparklinebullet"
  ],
  "Ext.sparkline.CanvasBase": [],
  "Ext.sparkline.CanvasCanvas": [],
  "Ext.sparkline.Discrete": [
    "widget.sparklinediscrete"
  ],
  "Ext.sparkline.Line": [
    "widget.sparklineline"
  ],
  "Ext.sparkline.Pie": [
    "widget.sparklinepie"
  ],
  "Ext.sparkline.RangeMap": [],
  "Ext.sparkline.Shape": [],
  "Ext.sparkline.TriState": [
    "widget.sparklinetristate"
  ],
  "Ext.sparkline.VmlCanvas": [],
  "Ext.state.CookieProvider": [],
  "Ext.state.LocalStorageProvider": [
    "state.localstorage"
  ],
  "Ext.state.Manager": [],
  "Ext.state.Provider": [],
  "Ext.state.Stateful": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.tip.QuickTip": [
    "widget.quicktip"
  ],
  "Ext.tip.QuickTipManager": [],
  "Ext.tip.Tip": [
    "widget.tip"
  ],
  "Ext.tip.ToolTip": [
    "widget.tooltip"
  ],
  "Ext.toolbar.Breadcrumb": [
    "widget.breadcrumb"
  ],
  "Ext.toolbar.Fill": [
    "widget.tbfill"
  ],
  "Ext.toolbar.Item": [
    "widget.tbitem"
  ],
  "Ext.toolbar.Paging": [
    "widget.pagingtoolbar"
  ],
  "Ext.toolbar.Separator": [
    "widget.tbseparator"
  ],
  "Ext.toolbar.Spacer": [
    "widget.tbspacer"
  ],
  "Ext.toolbar.TextItem": [
    "widget.tbtext"
  ],
  "Ext.toolbar.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.tree.Column": [
    "widget.treecolumn"
  ],
  "Ext.tree.NavigationModel": [
    "view.navigation.tree"
  ],
  "Ext.tree.Panel": [
    "widget.treepanel"
  ],
  "Ext.tree.View": [
    "widget.treeview"
  ],
  "Ext.tree.ViewDragZone": [],
  "Ext.tree.ViewDropZone": [],
  "Ext.tree.plugin.TreeViewDragDrop": [
    "plugin.treeviewdragdrop"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Animate": [],
  "Ext.util.Bag": [],
  "Ext.util.Base64": [],
  "Ext.util.CSS": [],
  "Ext.util.CSV": [],
  "Ext.util.ClickRepeater": [],
  "Ext.util.Collection": [],
  "Ext.util.CollectionKey": [],
  "Ext.util.ComponentDragger": [],
  "Ext.util.Cookies": [],
  "Ext.util.DelimitedValue": [],
  "Ext.util.ElementContainer": [],
  "Ext.util.Event": [],
  "Ext.util.Filter": [],
  "Ext.util.FilterCollection": [],
  "Ext.util.Floating": [],
  "Ext.util.FocusTrap": [],
  "Ext.util.Focusable": [],
  "Ext.util.FocusableContainer": [],
  "Ext.util.Format": [],
  "Ext.util.Group": [],
  "Ext.util.GroupCollection": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.History": [],
  "Ext.util.Inflector": [],
  "Ext.util.ItemCollection": [],
  "Ext.util.KeyMap": [],
  "Ext.util.KeyNav": [],
  "Ext.util.KeyboardInteractive": [],
  "Ext.util.LocalStorage": [],
  "Ext.util.LruCache": [],
  "Ext.util.Memento": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.ObjectTemplate": [],
  "Ext.util.Observable": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.Positionable": [],
  "Ext.util.ProtoElement": [],
  "Ext.util.Queue": [],
  "Ext.util.Region": [],
  "Ext.util.Renderable": [],
  "Ext.util.Schedulable": [],
  "Ext.util.Scheduler": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.SorterCollection": [],
  "Ext.util.StoreHolder": [],
  "Ext.util.TSV": [],
  "Ext.util.TaskManager": [],
  "Ext.util.TaskRunner": [],
  "Ext.util.TextMetrics": [],
  "Ext.util.Translatable": [],
  "Ext.util.XTemplateCompiler": [],
  "Ext.util.XTemplateParser": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollParent": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.Explorer": [
    "widget.explorer"
  ],
  "Ext.ux.FieldReplicator": [
    "plugin.fieldreplicator"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.TabReorderer": [
    "plugin.tabreorderer"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.colorpick.Button": [
    "widget.colorbutton"
  ],
  "Ext.ux.colorpick.ButtonController": [
    "controller.colorpick-buttoncontroller"
  ],
  "Ext.ux.colorpick.ColorMap": [
    "widget.colorpickercolormap"
  ],
  "Ext.ux.colorpick.ColorMapController": [
    "controller.colorpickercolormapcontroller"
  ],
  "Ext.ux.colorpick.ColorPreview": [
    "widget.colorpickercolorpreview"
  ],
  "Ext.ux.colorpick.ColorUtils": [],
  "Ext.ux.colorpick.Field": [
    "widget.colorfield"
  ],
  "Ext.ux.colorpick.Selection": [],
  "Ext.ux.colorpick.Selector": [
    "widget.colorselector"
  ],
  "Ext.ux.colorpick.SelectorController": [
    "controller.colorpick-selectorcontroller"
  ],
  "Ext.ux.colorpick.SelectorModel": [
    "viewmodel.colorpick-selectormodel"
  ],
  "Ext.ux.colorpick.Slider": [
    "widget.colorpickerslider"
  ],
  "Ext.ux.colorpick.SliderAlpha": [
    "widget.colorpickerslideralpha"
  ],
  "Ext.ux.colorpick.SliderController": [
    "controller.colorpick-slidercontroller"
  ],
  "Ext.ux.colorpick.SliderHue": [
    "widget.colorpickersliderhue"
  ],
  "Ext.ux.colorpick.SliderSaturation": [
    "widget.colorpickerslidersaturation"
  ],
  "Ext.ux.colorpick.SliderValue": [
    "widget.colorpickerslidervalue"
  ],
  "Ext.ux.dashboard.GoogleRssPart": [
    "part.google-rss"
  ],
  "Ext.ux.dashboard.GoogleRssView": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.desktop.App": [],
  "Ext.ux.desktop.Desktop": [
    "widget.desktop"
  ],
  "Ext.ux.desktop.Module": [],
  "Ext.ux.desktop.ShortcutModel": [],
  "Ext.ux.desktop.StartMenu": [],
  "Ext.ux.desktop.TaskBar": [
    "widget.taskbar"
  ],
  "Ext.ux.desktop.TrayClock": [
    "widget.trayclock"
  ],
  "Ext.ux.desktop.Video": [
    "widget.video"
  ],
  "Ext.ux.desktop.Wallpaper": [
    "widget.wallpaper"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.google.Api": [],
  "Ext.ux.google.Feeds": [],
  "Ext.ux.grid.SubTable": [
    "plugin.subtable"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.rating.Picker": [
    "widget.rating"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.view.AbstractView": [],
  "Ext.view.BoundList": [
    "widget.boundlist"
  ],
  "Ext.view.BoundListKeyNav": [
    "view.navigation.boundlist"
  ],
  "Ext.view.DragZone": [],
  "Ext.view.DropZone": [],
  "Ext.view.MultiSelector": [
    "widget.multiselector"
  ],
  "Ext.view.MultiSelectorSearch": [
    "widget.multiselector-search"
  ],
  "Ext.view.NavigationModel": [
    "view.navigation.default"
  ],
  "Ext.view.NodeCache": [],
  "Ext.view.Table": [
    "widget.gridview",
    "widget.tableview"
  ],
  "Ext.view.TableLayout": [
    "layout.tableview"
  ],
  "Ext.view.View": [
    "widget.dataview"
  ],
  "Ext.window.MessageBox": [
    "widget.messagebox"
  ],
  "Ext.window.Toast": [
    "widget.toast"
  ],
  "Ext.window.Window": [
    "widget.window"
  ]
});

Ext.setVersion("classic", "6.0.0");
Ext.setVersion("core", "5.0.0");
Ext.setVersion("ext", "6.0.0");

/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
Ext.Loader.loadScriptsSyncBasePrefix([]);

