Ext.define('RPMGridTabs.model.DealTitlesGridModel', {
    extend: 'Ext.data.Model',
    fields: [
             {name: 'termYear'},
	         {name: 'termYearDesc',              type: 'string'},
             {name: 'releaseYear',              type: 'int'},
             {name: 'fullTitle',                type: 'string'},
             {name: 'productType', 	          type: 'string'},
             {name: 'dealProductStatus', 	          type: 'string'},
	 	     {name: 'productFee',  		      type: 'number'},
	 	     {name: 'overageFee',      	      type: 'number'},
	 	     {name: 'otherFee',      	      type: 'number'},
	 	     {name:'totalLicenseFee',             type: 'number'},	 	    	 	   
	 	     {name: 'confirmedStatus', 	          type: 'string'},
	 	     {name: 'rightsDefined', 	      type: 'string'},
	 	     {name: 'keyCategory', 	  type: 'string'},
	 	     {name: 'pricingCategory', 	      type: 'string'},
	 	     {name: 'conflictOverride', 	      type: 'string'},
	 	     {name: 'conflictStatus', 	          type: 'string'},
	 	     {name: 'notes',   type: 'string'},
	 	     {name: 'countryOfOriginList', 	  type: 'string'},	 	     
 	         {name: 'sptiSalesRating', 	  type: 'string'},
 	         {name: 'runTimeMins', 	          type: 'string'},
	 	     {name: 'licenseStartDate',              type: 'date', dateFormat: 'time' },
 	         {name: 'licenseEndDate',                type: 'date', dateFormat: 'time'},
 	         {name:'firstRunRerunFlag',             type: 'string'},
             {name: 'qualifyingFlag',  	      type: 'string'},
             //{name: 'transactions',     type: 'string'},
             {name:'productionLanguage',                type: 'string'},
             {name: 'mpaaRating', 	 type: 'string'},
             {name: 'releasingCompanyList', 	 type: 'string'},          
             {name: 'productionBudget',          type: 'string'},
             {name: 'budgetCategoryId',          type: 'string'},
	         {name: 'usBoxOffice',              type: 'string'},
             {name: 'usBoxOfficeStatus',              type: 'string'},
             {name: 'usNumScreens',                type: 'string'},
             {name: 'usTheatDate', 	          type: 'string'},
             {name: 'usTheatStatus', 	          type: 'string'},
			 {name: 'localBoxOffice', 	  type: 'string'},
			 {name: 'usHeReleaseStatus',      	      type: 'string'},
	 	     {name: 'usHeReleaseDate',  		      type: 'string'},  
	 	     {name: 'usNetworkReleaseDate',      	      type: 'string'},
	 	     {name:'usNetworkReleaseStatus',             type: 'string'},
	 	     {name: 'usGenReleaseDate',      	      type: 'string'},
	 	     {name:'usGenReleaseStatus',             type: 'string'},
	 	     {name: 'usLtdReleaseDate',      	      type: 'string'},
	 	     {name:'usLtdReleaseStatus',             type: 'string'},
	 	     {name: 'usNetwork', 	          type: 'string'},
	 	     {name: 'localReleaseTitle', 	      type: 'string'},
	 	     {name: 'localBoxOfficeCurrency', 	      type: 'string'},
	 	     {name:'localAdmissions',            type: 'string'},
	 	     {name: 'localNumberOfScreens', 	      type: 'string'},
	 	     {name: 'localTheatricalReleaseDate', 	          type: 'string'},
	 	     {name: 'localTheatricalReleaseStatus',   type: 'string'},
	 	     {name: 'localHEReleaseDate', 	  type: 'string'},
	 	     {name: 'localHEReleaseStatus', 	          type: 'string'},
	 	     {name:'synopsis',              type: 'string'},
 	         {name: 'cast', 	  type: 'string'},
 	         {name: 'director', 	          type: 'string'},
	 	     {name: 'genre',              type: 'string'},
	 	     {name: 'intlProdFlag',                type: 'string'},
 	         {name:'opcNumber',             type: 'string'},
	 	     {name:'ownerProfitCenter',           type: 'string'},
             //{name: 'billingCategory',  	      type: 'string'},*/
             {name: 'productId',     type: 'int'},
			 {name:'lastStartOrderNumber',                type: 'string'},
             {name:'walkerNo',                type: 'string'},
             {name: 'userLogin', 	 type: 'string'},
             {name: 'lastModifiedDate', 	 type: 'date', dateReadFormat: 'Y-m-d'},
             {name: 'dealProductId', 	 type: 'int'},
             {name: 'rpmDealTermYearNumber', 	 type: 'string'},
             {name: 'keyCategoryId', 	 type: 'string'},
             {name: 'pricingCategoryId', 	 type: 'string'},
             {name: 'dealProductStatusStr', 	 type: 'string'},
             {name: 'seasonId', 	 type: 'string'},
             {name: 'summaryProductFeeTotal', 	 type: 'string'},
             {name: 'summaryOtherFeeTotal', 	 type: 'string'},
             {name: 'summaryOverageFeeTotal', 	 type: 'string'},
             {name: 'summaryTotalFee', 	 type: 'string'},
             {name: 'summaryDealProductStatus', 	 type: 'string'},
             {name: 'summaryStartDate', 	 type: 'string'},
             {name: 'summaryEndDate', 	 type: 'string'},
             {name: 'lowResVideoUrl', type: 'string'},
             {name: 'summaryProductId', 	 type: 'string'},
             {name: 'summaryReleaseYear', 	 type: 'string'},
             {name: 'summaryWalkerNo', type: 'string'},
             {name: 'summaryKeyCategory', 	 type: 'string'},
             {name: 'summaryPricingCategory', type: 'string'},
             {name: 'durationInMonths', type: 'string'},
             {name: 'durationInDays', type: 'string'},
             {name: 'durationInYear', type: 'string'},
             {name: 'estimatedFee', type: 'number'},
             {name: 'localPrintCount', type: 'string'},
             {name: 'uniqueKey', type : 'int'},
             {name: 'lowRiskAmount', type: 'string'},
             {name: 'medRiskAmount', type: 'string'},
             {name: 'highRiskAmount', type: 'string'},
             {name: 'revenueRecognitionDate', type: 'date', dateFormat: 'time'},
             {name: 'budgetCategoryName', type: 'string'},
             {name: 'alertIcon', type:'string'},
             {name : 'dealProductModified'},
             {name : 'excludeFromBudget'},
             {name: 'mergedProductTitle'},
             {name:'mergedProductId', type: 'int'}
	 	    ],
	 	    

	idProperty: 'uniqueKey'

});
