/*
 * File: app/view/mainContent.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TestApp.view.mainContent', {
    extend: 'Ext.container.Viewport',


    itemId: 'mainContent',
    layout: {
        type: 'absolute'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                            xtype: 'treepanel',
                            rootVisible: false,           //Code works if comment out this line
                            height: 442,
                            title: 'Users',
                            store: 'UserListTree',
                            animate: true,
                            useArrows: true
                }
            ]
        });

        me.callParent(arguments);
    }

});