/*
 * File: app/view/JourneyPlanner.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.JourneyPlanner', {
    extend: 'Ext.Container',

    config: {
        id: 'journeyPlanner',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'formpanel',
                id: 'JourneyPlannerDef',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Départ',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Nom'
                            },
                            {
                                xtype: 'button',
                                id: 'depBtn',
                                ui: 'action',
                                iconCls: 'search',
                                iconMask: true,
                                text: 'Définir'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Arrivée',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Nom'
                            },
                            {
                                xtype: 'button',
                                id: 'arrBtn',
                                ui: 'action',
                                iconCls: 'search',
                                iconMask: true,
                                text: 'Définir'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        id: 'DateHeure',
                        title: '',
                        layout: {
                            pack: 'center',
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'datepickerfield',
                                id: 'Date',
                                label: 'Jour',
                                placeHolder: '01/01/2012'
                            },
                            {
                                xtype: 'textfield',
                                id: 'Heure',
                                label: 'Heure',
                                value: '12:30'
                            },
                            {
                                xtype: 'segmentedbutton',
                                layout: {
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        text: 'Départ à'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Arrivée à'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'segmentedbutton',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                iconMask: true,
                                text: 'Le + rapide'
                            },
                            {
                                xtype: 'button',
                                iconMask: true,
                                text: 'Le - de chgt'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        height: 10
                    },
                    {
                        xtype: 'button',
                        ui: 'confirm',
                        text: 'Rechercher'
                    }
                ]
            }
        ]
    }

});